// ============================================================================
// SOVEREIGN — Project Fork Services (/home/toxic/projects/)
// All services are first-class and auto-started (no on-demand rollback)
// ============================================================================

import type { ServiceDef } from "../types/index.ts";

export const FORK_SERVICES: ServiceDef[] = [
  // ── BUILD / COMPILE TOOLCHAINS ──
  {
    id: "beellama-cpp",
    name: "beellama.cpp",
    portKey: "BEELLAMA_PORT",
    run: "exec /home/toxic/projects/beellama.cpp/build-cuda86/bin/llama-server --model ${EXAONE_1B_IQ4XS} --host 127.0.0.1 --port 25001 --n-gpu-layers all --flash-attn on --parallel 1 --metrics --mlock --no-mmap --cache-type-k q8_0 --cache-type-v q8_0 --ctx-size 32768 -b 2048 -ub 512",
    dir: "/home/toxic/projects/beellama.cpp",
    readyHttp: "/health",
    group: "infra",
    autoStart: true,
    mise: false,
    env: {
      LD_LIBRARY_PATH: "/home/toxic/projects/beellama.cpp/build-cuda86/bin",
      CUDA_VISIBLE_DEVICES: "0",
      GGML_CUDA: "1",
      GGML_CUDA_GRAPHS: "1",
      GGML_CUDA_FA_ALL_QUANTS: "1",
    },
  },
  {
    id: "ik-llama-cpp",
    name: "ik_llama.cpp",
    portKey: "IK_LLAMA_PORT",
    run: "exec /home/toxic/projects/ik_llama.cpp-main/build/bin/llama-server --model ${HERETIC_27B_Q5XL} --host 127.0.0.1 --port 25002 -ngl 99 --flash-attn on --fit --fit-margin 512 --no-warmup --defrag-thold 0.1 --cache-type-k q8_0 --cache-type-v q8_0 --ctx-size 65536",
    dir: "/home/toxic/projects/ik_llama.cpp-main",
    readyHttp: "/health",
    group: "infra",
    autoStart: true,
    mise: false,
    env: {
      LD_LIBRARY_PATH: "/home/toxic/projects/ik_llama.cpp-main/build/src:/home/toxic/projects/ik_llama.cpp-main/build/ggml/src:/home/toxic/projects/ik_llama.cpp-main/build/examples/mtmd",
      CUDA_VISIBLE_DEVICES: "0",
      GGML_CUDA: "1",
      GGML_CUDA_GRAPHS: "1",
      GGML_CUDA_FA_ALL_QUANTS: "1",
    },
  },
  {
    id: "llama-cpp-turboquant",
    name: "llama-cpp-turboquant",
    portKey: "TURBO_PORT",
    run: "exec /home/toxic/projects/llama-cpp-turboquant/build/bin/llama-server --model ${GEMMA_12B_BASE_Q4KM} --host 127.0.0.1 --port 25003 --n-gpu-layers all --flash-attn on --parallel 1 --metrics --mlock --no-mmap --cache-type-k turbo3 --cache-type-v turbo3 --ctx-size 98304",
    dir: "/home/toxic/projects/llama-cpp-turboquant",
    readyHttp: "/health",
    group: "infra",
    autoStart: true,
    mise: false,
    env: {
      LD_LIBRARY_PATH: "/home/toxic/projects/llama-cpp-turboquant/build/bin",
      CUDA_VISIBLE_DEVICES: "0",
      GGML_CUDA: "1",
      GGML_CUDA_GRAPHS: "1",
      GGML_CUDA_FA_ALL_QUANTS: "1",
    },
  },

  // ── AGENT RUNTIMES ──
  {
    id: "pi-agent",
    name: "pi-agent",
    portKey: "PI_AGENT_PORT",
    run: "exec bun run /home/toxic/projects/pi-agent/packages/coding-agent/src/cli.ts",
    dir: "/home/toxic",
    readyCmd: "sleep 2 && echo ready",
    group: "agent",
    autoStart: true,
    mise: true,
    env: {
      PI_CONFIG_PATH: "/home/toxic/.pi/agent/config.yaml",
      PI_AGENT_DIR: "/home/toxic/.pi/agent",
      PI_CODING_AGENT: "true",
      PI_REASONING_LEVEL: "high",
    },
  },
  {
    id: "kimi-code",
    name: "kimi-code-sovereign",
    portKey: "KIMI_CODE_PORT",
    run: "exec /home/toxic/projects/kimi-code-sovereign/apps/kimi-code/dist/main.mjs web --no-open --port 25126",
    dir: "/home/toxic/projects/kimi-code-sovereign",
    readyHttp: "/health",
    group: "main",
    autoStart: true,
    mise: true,
  },

  // ── GATEWAYS / PROXIES ──
  {
    id: "mcpproxy-go",
    name: "mcpproxy-go",
    portKey: "MCPPROXY_GO_PORT",
    run: "exec /home/toxic/projects/mcpproxy-go/mcpproxy-go serve --config=/home/toxic/.mcpproxy/mcp_config.json --log-level=info --port=25127",
    dir: "/home/toxic/projects/mcpproxy-go",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: false,
  },
  {
    id: "antigravity-gateway",
    name: "antigravity-gateway",
    portKey: "ANTIGRAVITY_GATEWAY_PORT",
    run: "exec bun --hot run src/gateway.ts",
    dir: "/home/toxic/projects/antigravity-gateway-master",
    readyHttp: "/",
    group: "main",
    autoStart: true,
    mise: true,
  },

  // ── EDITOR / IDE FORKS ──
  {
    id: "zed-editor",
    name: "zed-editor",
    portKey: "ZED_PORT",
    run: "exec ./target/release/zed --foreground",
    dir: "/home/toxic/projects/zed",
    readyHttp: "/health",
    group: "aux",
    autoStart: true,
    mise: false,
  },
  {
    id: "zedra-host",
    name: "zedra-host",
    portKey: "ZEDRA_HOST_PORT",
    run: "exec cargo run --bin zedra-host --release",
    dir: "/home/toxic/projects/zedra-tanlethanh",
    readyHttp: "/health",
    group: "aux",
    autoStart: true,
    mise: false,
  },

  // ── MCP SERVERS ──
  {
    id: "sovereign-github-search",
    name: "sovereign-github-search",
    portKey: "SOV_GHAS_PORT",
    run: "exec bun --hot run src/server.ts",
    dir: "/home/toxic/projects/sovereign-github-search",
    readyHttp: "/health",
    group: "search",
    autoStart: true,
    mise: true,
  },
  {
    id: "system-monitor-mcp",
    name: "system-monitor-mcp-fork",
    portKey: "SYS_MONITOR_PORT",
    run: "exec python3 /home/toxic/projects/system-monitor-mcp-fork/server.patched.py",
    dir: "/home/toxic/projects/system-monitor-mcp-fork",
    readyCmd: "sleep 2 && echo ready",
    group: "mcp",
    autoStart: true,
    mise: false,
    env: {
      PYTHONPATH: "/home/toxic/projects/system-monitor-mcp-fork/lib/home/toxic/.local/share/pipx/venvs/system-monitor-mcp/lib/python3.14/site-packages",
    },
    isMcpStdio: true,
  },
  {
    id: "wayland-mcp",
    name: "wayland-mcp",
    portKey: "WAYLAND_MCP_PORT",
    run: "exec /home/toxic/projects/wayland-mcp/venv/bin/python -m wayland_mcp.server_mcp",
    dir: "/home/toxic/projects/wayland-mcp",
    readyCmd: "sleep 3 && echo ready",
    group: "mcp",
    autoStart: true,
    mise: false,
    isMcpStdio: true,
  },

  // ── TOOLING ──
  {
    id: "antigravity-cli",
    name: "antigravity-cli",
    portKey: "ANTIGRAVITY_CLI_PORT",
    run: "exec cargo run --release -- --port 25134",
    dir: "/home/toxic/projects/antigravity-ide-cli",
    readyHttp: "/health",
    group: "aux",
    autoStart: true,
    mise: false,
  },
];
