// ============================================================================
// SOVEREIGN — Peripheral Services (Optional)
// ============================================================================

import type { ServiceDef } from "../types/index.ts";

export const PERIPHERAL_SERVICES: ServiceDef[] = [
  {
    id: "axiom",
    name: "axiom",
    portKey: "OPENFANG_PORT",
    run: "exec ./stack/services/openfang.sh",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/api/health",
  },
  {
    id: "rust-web",
    name: "rust-web",
    portKey: "RUST_WEB_BACKEND_PORT",
    run: "exec ./stack/services/rust-web-hot.sh",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "hf-downloader",
    name: "hf-downloader",
    portKey: "HF_DOWNLOADER_PORT",
    run: "exec ./stack/services/hf-downloader-mesh.sh",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    env: { HF_DOWNLOADER_PORT: "${HF_DOWNLOADER_PORT}" },
    healthPath: "/api/health",
  },
  {
    id: "pi-web-dashboard",
    name: "pi-web-dashboard",
    portKey: "PI_WEB_DASHBOARD_PORT",
    run: "exec /home/toxic/.bun/bin/bun run /home/toxic/projects/sovereign-projects/tau/engine/packages/server/dist/web-server.js",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    env: { PORT: "25192" },
    healthPath: "/api/health",
  },
  {
    id: "nginx",
    name: "nginx",
    portKey: "NGINX_PORT",
    run: "exec /usr/bin/nginx -c /etc/nginx/nginx.conf -g 'daemon off; pid /tmp/nginx-pitchfork.pid;'",
    dir: ".",
    readyCmd: "ss -ltn 'sport = :62200' | grep -q LISTEN",
    group: "aux",
    autoStart: true,
    mise: false,
  },
  {
    id: "flock",
    name: "flock",
    portKey: "FLOCK_PORT",
    run: "exec env HOST=127.0.0.1 PORT=8000 DATA_DIR=/home/toxic/.flock-data /home/toxic/.flock/flock", // nim-proxy absorbed by flock 2026-09-17
    dir: ".",
    readyCmd: "ss -ltn 'sport = :8000' | grep -q LISTEN",
    group: "aux",
    autoStart: true,
    mise: false,
  },
  {
    id: "matter-server",
    name: "matter-server",
    portKey: "MATTER_SERVER_PORT",
    run: "exec env STORAGE_PATH=/home/toxic/.matter_data BLUETOOTH_ADAPTER=0 LOG_LEVEL=info node --enable-source-maps /home/toxic/.matter-server/app/node_modules/matter-server/dist/esm/MatterServer.js --storage-path /home/toxic/.matter_data --bluetooth-adapter 0 --port 5580",
    dir: ".",
    readyCmd: "ss -ltn 'sport = :5580' | grep -q LISTEN",
    group: "aux",
    autoStart: true,
    mise: false,
  },
  {
    id: "browserless",
    name: "browserless",
    portKey: "BROWSERLESS_PORT",
    run: "exec /home/toxic/sovereign/projects/mesh/browserless/server/run.sh",
    dir: ".",
    readyCmd: "ss -ltn 'sport = :25130' | grep -q LISTEN",
    group: "aux",
    autoStart: true,
    mise: false,
  },
];
