// ============================================================================
// SOVEREIGN — Peripheral Services (Optional)
// ============================================================================

import type { ServiceDef } from "../types/index.ts";

export const PERIPHERAL_SERVICES: ServiceDef[] = [
  {
    id: "axiom",
    name: "axiom",
    portKey: "OPENFANG_PORT",
    run: "exec ./stack/services/openfang.sh",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/api/health",
  },
  {
    id: "rust-web",
    name: "rust-web",
    portKey: "RUST_WEB_BACKEND_PORT",
    run: "exec ./stack/services/rust-web-hot.sh",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "hf-downloader",
    name: "hf-downloader",
    portKey: "HF_DOWNLOADER_PORT",
    run: "exec ./stack/services/hf-downloader-mesh.sh",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    env: { HF_DOWNLOADER_PORT: "${HF_DOWNLOADER_PORT}" },
    healthPath: "/api/health",
  },
  {
    id: "pi-web-dashboard",
    name: "pi-web-dashboard",
    portKey: "PI_WEB_DASHBOARD_PORT",
    run: "exec /home/toxic/.bun/bin/bun run /home/toxic/projects/sovereign-projects/tau/engine/packages/server/dist/web-server.js",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    env: { PORT: "25192" },
    healthPath: "/api/health",
  },
  {
    id: "nginx",
    name: "nginx",
    portKey: "NGINX_PORT",
    run: "exec /usr/bin/nginx -c /etc/nginx/nginx.conf -g 'daemon off; pid /tmp/nginx-pitchfork.pid;'",
    dir: ".",
    readyCmd: "ss -ltn 'sport = :62200' | grep -q LISTEN",
    group: "aux",
    autoStart: true,
    mise: false,
  },
  {
    id: "nim-proxy",
    name: "nim-proxy",
    portKey: "NIM_PROXY_PORT",
    run: "exec docker run --rm --name nim-proxy -p 127.0.0.1:8000:8000 -v nim-proxy-data:/data -e DATA_DIR=/data ghcr.io/miztertea/nim-proxy:latest",
    dir: ".",
    readyCmd: "ss -ltn 'sport = :8000' | grep -q LISTEN",
    group: "aux",
    autoStart: true,
    mise: false,
  },
  {
    id: "matter-server",
    name: "matter-server",
    portKey: "MATTER_SERVER_PORT",
    run: "exec docker run --rm --name matter-server --net host -v /home/toxic/.matter_data:/data -v /run/dbus:/run/dbus:ro -e BLUETOOTH_ADAPTER=0 -e STORAGE_PATH=/data -e LOG_LEVEL=info ghcr.io/matter-js/matterjs-server:stable --storage-path /data --bluetooth-adapter 0",
    dir: ".",
    readyCmd: "ss -ltn 'sport = :5580' | grep -q LISTEN",
    group: "aux",
    autoStart: true,
    mise: false,
  },
];
