// ============================================================================
// SOVEREIGN — Unified Service Registry
// ============================================================================

import type { ServiceDef } from "../types/index.ts";

export const ALL_SERVICES: ServiceDef[] = [
  // ── CORE INFRASTRUCTURE ──
  {
    id: "herd",
    name: "herd",
    portKey: "HERD_PORT",
    run: "exec /home/toxic/sovereign/stack/services/herd.sh",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: false,
    healthPath: "/health",
  },
  {
    id: "qdrant",
    name: "qdrant",
    portKey: "QDRANT_PORT",
    run: "exec /home/toxic/.cargo/bin/qdrant-server --config-path ./qdrant-config.yaml",
    dir: ".",
    readyHttp: "/",
    group: "core",
    autoStart: true,
    mise: false,
    healthPath: "/",
  },
  {
    id: "redis",
    name: "redis",
    portKey: "REDIS_PORT",
    run: "exec valkey-server --port 25199 --bind 0.0.0.0 --protected-mode no --save '' --appendonly no",
    dir: ".",
    mise: false,
    retry: true,
    readyPort: true,
    group: "core",
    autoStart: true,
    healthPath: "/health",
  },
  {
    id: "kafka",
    name: "kafka",
    portKey: "KAFKA_PORT",
    run: "exec ./stack/services/kafka.sh",
    dir: ".",
    readyPort: true,
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "hal-substrate",
    name: "hal-substrate",
    portKey: "HAL_SUBSTRATE_PORT",
    run: "exec ./stack/services/hal-substrate.sh",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    depends: ["herd"],
    healthPath: "/health",
  },
  {
    id: "yote",
    name: "yote",
    portKey: "YOTE_PORT",
    run: "exec bun run src/services/yote.ts",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: false,
    healthPath: "/health",
  },

  // ── GHAS SERVICES ──
  // ── SEARCH SERVICES (GHAS / SEEKER) ──
  {
    id: "search-api",
    name: "search-api",
    portKey: "GHAS_API_PORT",
    run: "exec bun --hot run apps/api/src/server.ts",
    dir: "/home/toxic/projects/sovereign-projects/mesh/search",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    env: {},
    healthPath: "/health",
  },
  {
    id: "search-ui",
    name: "search-ui",
    portKey: "GHAS_FRONTEND_PORT",
    run: "exec ./node_modules/.bin/next dev -p 25114",
    dir: "/home/toxic/projects/sovereign-projects/mesh/search/apps/frontend",
    readyHttp: "/",
    group: "core",
    autoStart: true,
    mise: true,
    env: {},
    healthPath: "/",
  },

  // ── PERIPHERAL SERVICES ──
  {
    id: "axiom",
    name: "axiom",
    portKey: "OPENFANG_PORT",
    run: "exec ./stack/services/openfang.sh",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/api/health",
  },
  {
    id: "rust-web",
    name: "rust-web",
    portKey: "RUST_WEB_BACKEND_PORT",
    run: "exec ./stack/services/rust-web-hot.sh",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "hf-downloader",
    name: "hf-downloader",
    portKey: "HF_DOWNLOADER_PORT",
    run: "exec ./stack/services/hf-downloader-mesh.sh",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    env: {},
    healthPath: "/api/health",
  },
  {
    id: "null-g-proxy",
    name: "null-g-proxy",
    portKey: "NULL_G_PROXY_PORT",
    run: "exec bun run src/index.ts",
    dir: "/home/toxic/sovereign/tools/null-g-proxy",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "kimi-audit-dash",
    name: "kimi-audit-dash",
    portKey: "KIMI_AUDIT_DASH_PORT",
    run: "exec bun run /home/toxic/kimi-token-audit/dashboard/server.ts",
    dir: "/home/toxic/kimi-token-audit",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "mcp-gateway",
    name: "mcp-gateway",
    portKey: "MCP_GATEWAY_PORT",
    run: "exec bun run gateway.ts",
    dir: "/home/toxic/sovereign/tools/sovereign-router/sovereign-mcp-gateway",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "byte-vision",
    name: "byte-vision",
    portKey: "BYTE_VISION_PORT",
    run: "exec ./stack/services/byte-vision.sh",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "pi-web-dashboard",
    name: "pi-web-dashboard",
    portKey: "PI_WEB_DASHBOARD_PORT",
    run: "exec /home/toxic/.bun/bin/bun run /home/toxic/projects/sovereign-projects/tau/engine/packages/server/dist/web-server.js",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    env: { PORT: "25192" },
    healthPath: "/api/health",
  },

  // ── INFERENCE FLEET ENGINES (HERD) ──
  {
    id: "beellama-cpp",
    name: "beellama.cpp",
    portKey: "BEELLAMA_PORT",
    run: "exec /home/toxic/projects/sovereign-projects/herd/engines/beellama.cpp/build-cuda86/bin/llama-server --model /home/toxic/projects/models/EXAONE-4.0-1.2B-Q4_K_M.gguf --host 127.0.0.1 --port 25001 --n-gpu-layers 0 --parallel 1 --log-disable",
    dir: "/home/toxic/projects/sovereign-projects/herd/engines/beellama.cpp",
    readyHttp: "/health",
    group: "infra",
    autoStart: true,
    mise: false,
  },
  {
    id: "ik-llama-cpp",
    name: "ik_llama.cpp",
    portKey: "IK_LLAMA_PORT",
    run: "exec /home/toxic/projects/sovereign-projects/herd/engines/ik_llama.cpp/build/bin/llama-server --model /home/toxic/projects/models/heretic-UD-27B-Q5_K_XL.gguf --host 127.0.0.1 --port 25002 -ngl 0 --parallel 1 --log-disable",
    dir: "/home/toxic/projects/sovereign-projects/herd/engines/ik_llama.cpp",
    readyHttp: "/health",
    group: "infra",
    autoStart: true,
    mise: false,
  },
  {
    id: "llama-cpp-turboquant",
    name: "llama-cpp-turboquant",
    portKey: "TURBO_PORT",
    run: "exec /home/toxic/projects/sovereign-projects/herd/engines/llama-cpp-turboquant/build/bin/llama-server --model /home/toxic/projects/models/gemma4-31b-it-dflash-Q4_K_M.gguf --host 127.0.0.1 --port 25003 --n-gpu-layers 0 --parallel 1 --log-disable",
    dir: "/home/toxic/projects/sovereign-projects/herd/engines/llama-cpp-turboquant",
    readyHttp: "/health",
    group: "infra",
    autoStart: true,
    mise: false,
  },

  // ── AGENT RUNTIMES (TAU) ──
  {
    id: "tau",
    name: "tau",
    portKey: "PI_AGENT_PORT",
    run: "exec bun run /home/toxic/projects/sovereign-projects/tau/engine/packages/coding-agent/src/cli.ts",
    dir: "/home/toxic",
    readyCmd: "sleep 2 && echo ready",
    group: "agents",
    autoStart: true,
    mise: true,
    env: {
      PI_CONFIG_PATH: "/home/toxic/.pi/agent/config.yaml",
      PI_AGENT_DIR: "/home/toxic/.pi/agent",
      PI_CODING_AGENT: "true",
      PI_REASONING_LEVEL: "high",
    },
  },
  {
    id: "kimi-code",
    name: "kimi-code-sovereign",
    portKey: "KIMI_CODE_PORT",
    run: "exec /home/toxic/projects/sovereign-projects/tau/kimi/apps/kimi-code/dist/main.mjs web --no-open --port 25126",
    dir: "/home/toxic/projects/sovereign-projects/tau/kimi",
    readyHttp: "/health",
    group: "main",
    autoStart: true,
    mise: true,
  },

  // ── GATEWAYS / PROXIES (MESH) ──
  {
    id: "mesh",
    name: "mesh",
    portKey: "MCPPROXY_GO_PORT",
    run: "exec /home/toxic/projects/sovereign-projects/mesh/gateway/mcpproxy-go serve --config=/home/toxic/.mcpproxy/mcp_config.json --log-level=info --listen=127.0.0.1:25127",
    dir: "/home/toxic/projects/sovereign-projects/mesh/gateway",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: false,
  },

  // ── EDITOR / IDE FORKS (QED) ──
  {
    id: "qed",
    name: "qed",
    portKey: "ZED_PORT",
    run: "exec ./target/release/zed --foreground",
    dir: "/home/toxic/projects/sovereign-projects/qed/editor",
    readyHttp: "/health",
    group: "aux",
    autoStart: true,
    mise: false,
  },
  {
    id: "zedra-host",
    name: "zedra-host",
    portKey: "ZEDRA_HOST_PORT",
    run: "exec cargo run --bin zedra-host --release",
    dir: "/home/toxic/projects/sovereign-projects/qed/zedra-host",
    readyHttp: "/health",
    group: "aux",
    autoStart: true,
    mise: false,
  },

  // ── TOOLING ──
  {
    id: "antigravity-cli",
    name: "antigravity-cli",
    portKey: "ANTIGRAVITY_CLI_PORT",
    run: "exec cargo run --release -- --port 25134",
    dir: "/home/toxic/projects/sovereign-projects/mesh/tooling",
    readyHttp: "/health",
    group: "aux",
    autoStart: true,
    mise: false,
  },
];
