// ============================================================================
// SOVEREIGN — Unified Service Registry
// ============================================================================

import type { ServiceDef } from "../types/index.ts";

export const ALL_SERVICES: ServiceDef[] = [
  // ── CORE INFRASTRUCTURE ──
  {
    id: "herd",
    name: "herd",
    portKey: "HERD_PORT",
    run: "exec /home/toxic/sovereign/stack/services/herd.sh",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: false,
    healthPath: "/health",
  },
  {
    id: "qdrant",
    name: "qdrant",
    portKey: "QDRANT_PORT",
    run: "exec /home/toxic/.cargo/bin/qdrant-server --config-path ./qdrant-config.yaml",
    dir: ".",
    readyHttp: "/",
    group: "core",
    autoStart: true,
    mise: false,
    healthPath: "/",
  },
  {
    id: "redis",
    name: "redis",
    portKey: "REDIS_PORT",
    run: "exec valkey-server --port 25199 --bind 0.0.0.0 --protected-mode no --save '' --appendonly no",
    dir: ".",
    mise: false,
    retry: true,
    readyPort: true,
    group: "core",
    autoStart: true,
    healthPath: "/health",
  },
  {
    id: "kafka",
    name: "kafka",
    portKey: "KAFKA_PORT",
    run: "exec ./stack/services/kafka.sh",
    dir: ".",
    readyPort: true,
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "hal-substrate",
    name: "hal-substrate",
    portKey: "HAL_SUBSTRATE_PORT",
    run: "exec ./stack/services/hal-substrate.sh",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    depends: ["herd"],
    healthPath: "/health",
  },
  {
    id: "yote",
    name: "yote",
    portKey: "YOTE_PORT",
    run: "exec bun run src/services/yote.ts",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: false,
    healthPath: "/health",
  },
  {
    id: "tailscaled",
    name: "tailscaled",
    portKey: "TAILSCALED_PORT",
    run: "exec /home/toxic/sovereign/stack/services/tailscaled.sh",
    dir: ".",
    group: "core",
    autoStart: true,
    mise: true,
  },

  // ── GHAS & SEARCH SERVICES ──
  {
    id: "search-api",
    name: "search-api",
    portKey: "GHAS_API_PORT",
    run: "exec bun --hot run apps/api/src/server.ts",
    dir: "/home/toxic/projects/sovereign-projects/sovereign-github-search",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    env: {},
    healthPath: "/health",
  },
  {
    id: "ghas-mcp",
    name: "ghas-mcp",
    portKey: "GHAS_MCP_PORT",
    run: "exec bun run apps/mcp/src/server.ts --mode http",
    dir: "/home/toxic/projects/sovereign-projects/sovereign-github-search",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    env: { GHAS_MCP_PORT: "25113" },
    healthPath: "/health",
  },
  {
    id: "search-ui",
    name: "search-ui",
    portKey: "GHAS_FRONTEND_PORT",
    run: "exec ./node_modules/.bin/next dev -p 25114",
    dir: "/home/toxic/projects/sovereign-projects/sovereign-github-search/apps/frontend",
    readyHttp: "/",
    group: "core",
    autoStart: true,
    mise: true,
    env: {},
    healthPath: "/",
  },
  {
    id: "mesh-hub",
    name: "mesh-hub",
    portKey: "MESH_HUB_PORT",
    run: "exec bun run src/services/mesh-hub.ts",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },

  // ── PERIPHERAL SERVICES ──
  {
    id: "axiom",
    name: "axiom",
    portKey: "OPENFANG_PORT",
    run: "exec ./stack/services/openfang.sh",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/api/health",
  },
  {
    id: "rust-web",
    name: "rust-web",
    portKey: "RUST_WEB_BACKEND_PORT",
    run: "exec ./stack/services/rust-web-hot.sh",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "hf-downloader",
    name: "hf-downloader",
    portKey: "HF_DOWNLOADER_PORT",
    run: "exec ./stack/services/hf-downloader-mesh.sh",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    env: {},
    healthPath: "/api/health",
  },
  {
    id: "null-g-proxy",
    name: "null-g-proxy",
    portKey: "NULL_G_PROXY_PORT",
    run: "exec bun run src/index.ts",
    dir: "/home/toxic/sovereign/tools/null-g-proxy",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "kimi-audit-dash",
    name: "kimi-audit-dash",
    portKey: "KIMI_AUDIT_DASH_PORT",
    run: "exec bun run /home/toxic/kimi-token-audit/dashboard/server.ts",
    dir: "/home/toxic/kimi-token-audit",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "mcp-gateway",
    name: "mcp-gateway",
    portKey: "MCP_GATEWAY_PORT",
    run: "exec bun run gateway.ts",
    dir: "/home/toxic/sovereign/tools/sovereign-router/sovereign-mcp-gateway",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "byte-vision",
    name: "byte-vision",
    portKey: "BYTE_VISION_PORT",
    run: "exec ./stack/services/byte-vision.sh",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/health",
  },
  {
    id: "pi-web-dashboard",
    name: "pi-web-dashboard",
    portKey: "PI_WEB_DASHBOARD_PORT",
    run: "exec /home/toxic/.bun/bin/bun run /home/toxic/projects/sovereign-projects/tau/engine/packages/server/dist/web-server.js",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    env: { PORT: "25192" },
    healthPath: "/api/health",
  },
  {
    id: "hindsight",
    name: "hindsight",
    portKey: "HINDSIGHT_API_PORT",
    run: "exec ./stack/services/hindsight.sh",
    dir: ".",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: false,
    healthPath: "/health",
  },

  // ── MONITORING ──
  {
    id: "prometheus",
    name: "prometheus",
    portKey: "PROMETHEUS_PORT",
    run: "exec ./stack/services/prometheus-hot.sh",
    dir: ".",
    readyHttp: "/-/healthy",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/-/healthy",
  },
  {
    id: "grafana",
    name: "grafana",
    portKey: "GRAFANA_PORT",
    run: "exec ./stack/services/grafana-mesh.sh",
    dir: ".",
    readyHttp: "/api/health",
    group: "core",
    autoStart: true,
    mise: true,
    healthPath: "/api/health",
  },

  // ── AGENT RUNTIMES (TAU) ──
  {
    id: "tau",
    name: "tau",
    portKey: "PI_AGENT_PORT",
    run: "exec bun run /home/toxic/projects/sovereign-projects/tau/packages/coding-agent/src/cli.ts",
    dir: "/home/toxic",
    readyCmd: "sleep 2 && echo ready",
    group: "agents",
    autoStart: true,
    mise: true,
    env: {
      PI_CONFIG_PATH: "/home/toxic/.pi/agent/config.yaml",
      PI_AGENT_DIR: "/home/toxic/.pi/agent",
      PI_CODING_AGENT: "true",
      PI_REASONING_LEVEL: "high",
    },
  },
  {
    id: "kimi-code",
    name: "kimi-code-sovereign",
    portKey: "KIMI_CODE_PORT",
    run: "exec /home/toxic/projects/sovereign-projects/tau/kimi/apps/kimi-code/dist/main.mjs web --no-open --port 25126",
    dir: "/home/toxic/projects/sovereign-projects/tau/kimi",
    readyHttp: "/health",
    group: "main",
    autoStart: true,
    mise: true,
  },

  // ── GATEWAYS / PROXIES (MESH) ──
  {
    id: "mesh",
    name: "mesh",
    portKey: "MCPPROXY_GO_PORT",
    run: "exec /home/toxic/projects/sovereign-projects/mesh/gateway/mcpproxy-go serve --config=/home/toxic/.mcpproxy/mcp_config.json --log-level=info --listen=127.0.0.1:25127",
    dir: "/home/toxic/projects/sovereign-projects/mesh/gateway",
    readyHttp: "/health",
    group: "core",
    autoStart: true,
    mise: false,
  },
];
