ios_deployment_target = '16.0'

platform :ios, ios_deployment_target
use_frameworks! :linkage => :static

target 'Zedra' do
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'GoogleSignIn'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Xcode 26 warns on older podspec defaults; the app only supports iOS 16+.
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ios_deployment_target
    end
  end
end
