blank_issues_enabled: true
contact_links:
  - name: Zedra Website
    url: https://zedra.dev
    about: Learn more about Zedra.
  - name: Discord
    url: https://discord.gg/39MmkSS8sc
    about: Discuss questions and ideas with the community.
