package main

import (
	"archive/tar"
	"archive/zip"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// update_apply.go holds the mechanical half of `mcpproxy update`'s self-update
// (Spec 092 FR-021): integrity verification, archive extraction, and the
// atomic binary swap. It is deliberately free of cobra and of network code so
// every rule below is unit-testable against real files in a t.TempDir().

const (
	// maxArchiveMemberBytes bounds a single extracted archive member. The core
	// binary is ~60-90 MB; the cap exists so a malicious archive cannot fill
	// the disk before the checksum comparison would have rejected it.
	maxArchiveMemberBytes = 512 << 20

	// verifyExecTimeout bounds the post-swap `<new binary> --version` probe
	// (FR-021: success means the new binary actually runs).
	verifyExecTimeout = 30 * time.Second

	// swapSentinelSuffix names the file that marks a binary swap as in
	// progress. Present only between "about to move the current binary aside"
	// and "the replacement verified", so finding one means a swap died
	// halfway. See applyNewBinary.
	swapSentinelSuffix = ".updating"

	// backupSuffix names the copy of the previous binary kept until the new
	// one has proved itself. Named rather than inlined because
	// canonicalUpdateTarget has to recognise it.
	backupSuffix = ".old"
)

// parseChecksums parses a sha256sum-format manifest ("<hex>  <name>" or
// "<hex> *<name>") into name -> lowercase hex digest. Unparseable lines are
// skipped rather than failing the whole file: the manifest is generated by CI
// and a future extra line must not break verification of the entry we need.
func parseChecksums(r io.Reader) (map[string]string, error) {
	data, err := io.ReadAll(io.LimitReader(r, 4<<20))
	if err != nil {
		return nil, fmt.Errorf("read checksums: %w", err)
	}
	out := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		digest := strings.ToLower(fields[0])
		if len(digest) != 64 {
			continue
		}
		if _, err := hex.DecodeString(digest); err != nil {
			continue
		}
		name := strings.TrimPrefix(fields[len(fields)-1], "*")
		name = strings.TrimPrefix(name, "./")
		out[name] = digest
	}
	if len(out) == 0 {
		return nil, errors.New("checksums manifest contains no usable entries")
	}
	return out, nil
}

// verifyFileSHA256 hard-fails unless path hashes to wantHex.
func verifyFileSHA256(path, wantHex string) error {
	f, err := os.Open(path) // #nosec G304 -- path is a file this process just downloaded into its own temp dir
	if err != nil {
		return fmt.Errorf("open downloaded artifact: %w", err)
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return fmt.Errorf("hash downloaded artifact: %w", err)
	}
	got := hex.EncodeToString(h.Sum(nil))
	if !strings.EqualFold(got, wantHex) {
		return fmt.Errorf("checksum mismatch for %s: manifest says %s, download is %s (nothing was installed)",
			filepath.Base(path), wantHex, got)
	}
	return nil
}

// extractBinary pulls the single archive member named memberName (matched on
// base name, so a future archive that nests files still works) into destPath,
// which is created with mode 0o700 — the caller re-applies the real mode when
// swapping it into place.
func extractBinary(archivePath, memberName, destPath string) error {
	switch {
	case strings.HasSuffix(archivePath, ".zip"):
		return extractFromZip(archivePath, memberName, destPath)
	case strings.HasSuffix(archivePath, ".tar.gz"), strings.HasSuffix(archivePath, ".tgz"):
		return extractFromTarGz(archivePath, memberName, destPath)
	default:
		return fmt.Errorf("unsupported archive format: %s", filepath.Base(archivePath))
	}
}

func extractFromTarGz(archivePath, memberName, destPath string) error {
	f, err := os.Open(archivePath) // #nosec G304 -- self-downloaded temp file
	if err != nil {
		return fmt.Errorf("open archive: %w", err)
	}
	defer f.Close()

	gz, err := gzip.NewReader(f)
	if err != nil {
		return fmt.Errorf("open gzip stream: %w", err)
	}
	defer gz.Close()

	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return fmt.Errorf("read archive: %w", err)
		}
		if hdr.Typeflag != tar.TypeReg || filepath.Base(hdr.Name) != memberName {
			continue
		}
		return writeMember(tr, destPath)
	}
	return fmt.Errorf("archive does not contain %q", memberName)
}

func extractFromZip(archivePath, memberName, destPath string) error {
	zr, err := zip.OpenReader(archivePath)
	if err != nil {
		return fmt.Errorf("open archive: %w", err)
	}
	defer zr.Close()

	for _, entry := range zr.File {
		if entry.FileInfo().IsDir() || filepath.Base(entry.Name) != memberName {
			continue
		}
		rc, err := entry.Open()
		if err != nil {
			return fmt.Errorf("open archive member: %w", err)
		}
		defer rc.Close()
		return writeMember(rc, destPath)
	}
	return fmt.Errorf("archive does not contain %q", memberName)
}

// writeMember copies at most maxArchiveMemberBytes from r into destPath.
func writeMember(r io.Reader, destPath string) error {
	out, err := os.OpenFile(destPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC|os.O_EXCL, 0o700) // #nosec G304 -- destPath is our own temp path
	if err != nil {
		return fmt.Errorf("create staged binary: %w", err)
	}
	written, err := io.Copy(out, io.LimitReader(r, maxArchiveMemberBytes+1))
	if err != nil {
		out.Close()
		return fmt.Errorf("write staged binary: %w", err)
	}
	if written > maxArchiveMemberBytes {
		out.Close()
		return fmt.Errorf("archive member exceeds the %d-byte limit", int64(maxArchiveMemberBytes))
	}
	if err := out.Sync(); err != nil {
		out.Close()
		return fmt.Errorf("flush staged binary: %w", err)
	}
	return out.Close()
}

// ensureTargetWritable reports why the binary cannot be replaced, naming the
// path and its owner. It never suggests (let alone performs) privilege
// escalation: a root-owned install belongs to whoever installed it (FR-022).
func ensureTargetWritable(target string) error {
	dir := filepath.Dir(target)

	probe, err := os.CreateTemp(dir, ".mcpproxy-update-probe-*")
	if err != nil {
		return fmt.Errorf(
			"cannot update %s: its directory %s is not writable by the current user (%s).\n"+
				"mcpproxy never escalates privileges. Either reinstall through whatever owns that path, "+
				"or install a copy somewhere you own (e.g. ~/.local/bin) and update that one",
			target, dir, describeOwner(dir))
	}
	name := probe.Name()
	probe.Close()
	if err := os.Remove(name); err != nil {
		return fmt.Errorf("cannot clean up write probe %s: %w", name, err)
	}
	return nil
}

// applyNewBinary swaps staged into target atomically (FR-021):
// rename target -> target.old, rename staged -> target, then prove the new
// binary runs. The previous binary is restored on any failure and only removed
// once verification passed. Callers must pass an already-resolved (symlink
// free) target so a symlinked launcher keeps pointing at the file we replace.
//
// The two renames are individually atomic but the sequence is not, so a crash
// can land in one of two windows, and the two look different on disk:
//
//	between the renames  → target absent, backup holds the only copy;
//	after the renames    → target holds an UNVERIFIED binary, backup holds the
//	                       last known-good one.
//
// The second is the dangerous one, because on disk it is indistinguishable
// from a finished update — and a retry that mistakes it for one deletes the
// backup, which is the last known-good binary there is. So the swap writes a
// sentinel next to the target for exactly as long as it is in progress, and
// recovery reads it to tell the two states apart. Nothing removes the backup
// while the sentinel exists.
func applyNewBinary(target, staged string, verify func(path string) error) (err error) {
	// Before anything else, and before the lock: a target that is itself one of
	// our working files means the path we were handed is an alias for a binary
	// some other update owns. Swapping it would move that update's backup out
	// from under it — the lock cannot help, because the two processes would be
	// naming different files.
	if aliasErr := refuseAliasedUpdateTarget(target); aliasErr != nil {
		return aliasErr
	}

	backup := target + backupSuffix
	sentinel := target + swapSentinelSuffix

	// The whole recover-and-swap sequence runs under an exclusive per-target
	// lock: a concurrent invocation reading a sibling's sentinel/backup state
	// mid-swap would misclassify it and could delete the only known-good
	// backup. Crash-safe (the kernel releases it with the process).
	release, lockErr := acquireUpdateLock(target)
	if lockErr != nil {
		return lockErr
	}
	defer release()

	if recoverErr := recoverInterruptedSwap(target, backup, sentinel, verify); recoverErr != nil {
		return recoverErr
	}

	mode := os.FileMode(0o755)
	if fi, statErr := os.Stat(target); statErr == nil {
		mode = fi.Mode().Perm()
	}
	if chmodErr := os.Chmod(staged, mode); chmodErr != nil {
		return fmt.Errorf("preserve file mode %o: %w", mode, chmodErr)
	}

	// The target is present and known-good (recoverInterruptedSwap guarantees
	// both), so a leftover .old is genuinely expendable. Done BEFORE the
	// sentinel goes down, so "sentinel exists" never coincides with a backup
	// being deleted.
	_ = os.Remove(backup)

	if sentinelErr := writeSwapSentinel(sentinel, staged); sentinelErr != nil {
		return sentinelErr
	}
	// Removed on every path this function RETURNS by — success or handled
	// failure — because each of those ends with the filesystem consistent. Only
	// a crash leaves it behind, which is exactly what it is for.
	defer func() { _ = os.Remove(sentinel) }()

	if renameErr := os.Rename(target, backup); renameErr != nil {
		return fmt.Errorf("move current binary aside: %w", renameErr)
	}

	restore := func() {
		_ = os.Remove(target)
		if restoreErr := os.Rename(backup, target); restoreErr != nil {
			// Nothing left to try; make the situation explicit so the user can
			// recover by hand instead of discovering a missing binary later.
			fmt.Fprintf(os.Stderr,
				"CRITICAL: failed to restore the previous binary. It is at %s — move it back to %s manually: %v\n",
				backup, target, restoreErr)
		}
	}

	if renameErr := os.Rename(staged, target); renameErr != nil {
		restore()
		return fmt.Errorf("install new binary: %w", renameErr)
	}

	if verify != nil {
		if verifyErr := verify(target); verifyErr != nil {
			restore()
			return fmt.Errorf("new binary failed verification, previous version restored: %w", verifyErr)
		}
	}

	// Only now is the old binary expendable (FR-021).
	if rmErr := os.Remove(backup); rmErr != nil {
		// Non-fatal: the update succeeded, there is just a stale .old file.
		fmt.Fprintf(os.Stderr, "note: could not remove %s: %v\n", backup, rmErr)
	}
	return nil
}

// writeSwapSentinel marks the target as mid-swap.
//
// Best-effort durability: the content is fsynced, but the directory entry is
// not, so a power cut can still lose the file. That is the same guarantee the
// renames themselves have, and the failure it would reintroduce is the one
// that existed before the sentinel — not a new one.
func writeSwapSentinel(sentinel, staged string) error {
	f, err := os.OpenFile(sentinel, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600) // #nosec G304 -- derived from the caller-resolved target path
	if err != nil {
		return fmt.Errorf("mark the update in progress (%s): %w", sentinel, err)
	}
	fmt.Fprintf(f, "mcpproxy is replacing this binary with %s (pid %d, %s).\n"+
		"If this file is still here, the update did not finish; mcpproxy will\n"+
		"repair it on the next run. Do not delete the .old file by hand.\n",
		staged, os.Getpid(), time.Now().UTC().Format(time.RFC3339))
	if syncErr := f.Sync(); syncErr != nil {
		f.Close()
		return fmt.Errorf("flush %s: %w", sentinel, syncErr)
	}
	return f.Close()
}

// recoverInterruptedSwap puts the world back together after a crash inside
// applyNewBinary, and is the reason the sentinel exists.
//
// With the sentinel present, target and backup between them say exactly how
// far the interrupted swap got:
//
//	neither          → nothing to recover from and nothing to install onto
//	backup only      → crashed between the renames; the backup is the only copy
//	target only      → crashed before the first rename; the target is original
//	target + backup  → crashed after the second rename; the target was NEVER
//	                   verified and the backup is the last known-good binary
//
// Only the last case needs a judgement, and it is made by running the caller's
// verification against what is at the target: it either proves itself or the
// known-good binary goes back. Without a verifier there is no way to prove it,
// so the known-good binary wins by default.
func recoverInterruptedSwap(target, backup, sentinel string, verify func(path string) error) error {
	interrupted, err := regularFileExists(sentinel)
	if err != nil {
		return fmt.Errorf("inspect %s: %w", sentinel, err)
	}
	targetExists, err := regularFileExists(target)
	if err != nil {
		return fmt.Errorf("inspect %s: %w", target, err)
	}
	backupExists, err := regularFileExists(backup)
	if err != nil {
		return fmt.Errorf("inspect %s: %w", backup, err)
	}

	if !interrupted {
		switch {
		case targetExists:
			return nil
		case backupExists:
			// No sentinel, no target: a swap interrupted by a build that
			// predates the sentinel. The backup is still the only copy.
			return restoreKnownGood(target, backup, "a previous update was interrupted")
		default:
			return fmt.Errorf("%s does not exist and there is no %s to restore from; "+
				"reinstall mcpproxy rather than letting an update invent a binary", target, backup)
		}
	}

	clearSentinel := func() {
		if rmErr := os.Remove(sentinel); rmErr != nil {
			fmt.Fprintf(os.Stderr, "note: could not remove %s: %v\n", sentinel, rmErr)
		}
	}

	switch {
	case !targetExists && !backupExists:
		return fmt.Errorf("an update of %s was interrupted and neither the binary nor %s is there; "+
			"reinstall mcpproxy", target, backup)

	case !targetExists:
		if restoreErr := restoreKnownGood(target, backup,
			"an update was interrupted between replacing the binary and putting the new one in place"); restoreErr != nil {
			return restoreErr
		}
		clearSentinel()
		return nil

	case !backupExists:
		// The swap never got as far as moving anything: what is at the target
		// is the binary that was there all along.
		clearSentinel()
		return nil
	}

	// Both present. What is at the target came from an update that never
	// finished proving itself.
	if verify == nil {
		if restoreErr := restoreKnownGood(target, backup,
			"an update was interrupted before the new binary could be verified, and this run cannot verify it either"); restoreErr != nil {
			return restoreErr
		}
		clearSentinel()
		return nil
	}
	if verifyErr := verify(target); verifyErr != nil {
		if restoreErr := restoreKnownGood(target, backup, fmt.Sprintf(
			"an update was interrupted and left an unusable binary at %s (%v)", target, verifyErr)); restoreErr != nil {
			return restoreErr
		}
		clearSentinel()
		return nil
	}

	// It verifies: the interrupted run had in fact succeeded and only died
	// before tidying up. The backup has served its purpose.
	fmt.Fprintf(os.Stderr,
		"note: a previous update of %s had completed; cleaning up after it\n", target)
	if rmErr := os.Remove(backup); rmErr != nil {
		fmt.Fprintf(os.Stderr, "note: could not remove %s: %v\n", backup, rmErr)
	}
	clearSentinel()
	return nil
}

// restoreKnownGood moves backup back over target. os.Rename replaces an
// existing target, which is what discards an unverified binary.
func restoreKnownGood(target, backup, why string) error {
	if renameErr := os.Rename(backup, target); renameErr != nil {
		return fmt.Errorf("%s: %s holds the last known-good binary and it could not be moved "+
			"back to %s: %w", why, backup, target, renameErr)
	}
	fmt.Fprintf(os.Stderr, "note: %s; restored %s from %s\n", why, target, backup)
	return nil
}

func regularFileExists(path string) (bool, error) {
	fi, err := os.Lstat(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return false, nil
		}
		return false, err
	}
	return fi.Mode().IsRegular(), nil
}

// verifyInstalledVersion runs `<path> --version` and requires the output to
// mention wantVersion. FR-021: "success" is the new binary executing and
// reporting the expected version, not merely a rename returning nil.
func verifyInstalledVersion(path, wantVersion string) error {
	ctx, cancel := context.WithTimeout(context.Background(), verifyExecTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, path, "--version") // #nosec G204 -- path is the binary we just installed at a caller-resolved location
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("running %s --version failed: %w (output: %s)",
			filepath.Base(path), err, strings.TrimSpace(string(out)))
	}
	got := strings.TrimSpace(string(out))
	if !reportsVersion(got, wantVersion) {
		return fmt.Errorf("installed binary reports %q, expected version %s", got, wantVersion)
	}
	return nil
}

// reportsVersion reports whether output announces exactly wantVersion.
//
// Whole tokens, not a substring: `mcpproxy --version` prints
// "MCPProxy 0.54.10 (personal) darwin/arm64", and a substring test would let
// that output satisfy a request for 0.54.1 — an update that silently installed
// the wrong release would pass verification.
func reportsVersion(output, wantVersion string) bool {
	want := strings.TrimPrefix(strings.TrimSpace(wantVersion), "v")
	if want == "" {
		return false
	}
	for _, field := range strings.Fields(output) {
		token := strings.TrimPrefix(strings.Trim(field, "(),;\"'"), "v")
		if token == want {
			return true
		}
	}
	return false
}
