#!/bin/sh
# Xcode Cloud — ci_pre_xcodebuild.sh
#
# Runs AFTER pod install and BEFORE xcodebuild archive/test.
# This is where the Rust library is compiled into ZedraFFI.xcframework.
#
# By this point:
#   - Rust + aarch64-apple-ios target are installed (from ci_post_clone.sh)
#   - Zedra.xcodeproj exists (generated in ci_post_clone.sh)
#   - Zedra.xcworkspace exists (generated by Xcode Cloud's automatic pod install)
#   - ZedraFFI.xcframework directory is present but its .a slices are absent
#     (the .a files are gitignored; they must be built by this script)
#
# Xcode Cloud environment variables used here:
#   CI_XCODEBUILD_ACTION   "archive", "test", etc. — skip Rust build for non-archive actions
#   CI_CONFIGURATION       "Release" or "Debug"
#   CI_PRIMARY_REPOSITORY_PATH  repo root

set -euo pipefail

echo "==> ci_pre_xcodebuild: action=$CI_XCODEBUILD_ACTION"
cd "$CI_PRIMARY_REPOSITORY_PATH"

# Source the Rust environment installed in ci_post_clone.sh.
# $HOME is the same user across all custom scripts in a single build.
# shellcheck source=/dev/null
. "$HOME/.cargo/env"

echo "==> Rust version: $(rustc --version)"

# ── Determine build profile ──────────────────────────────────────────────────
# Use --release for archive (App Store) builds; debug otherwise.
RUST_PROFILE_FLAG=""
if [ "${CI_CONFIGURATION:-}" = "Release" ] || [ "${CI_XCODEBUILD_ACTION:-}" = "archive" ]; then
    RUST_PROFILE_FLAG="--release"
    echo "==> Using release profile"
else
    echo "==> Using debug profile"
fi

# ── Build Rust xcframework ───────────────────────────────────────────────────
# --device builds only the aarch64-apple-ios slice (no simulator slice needed
# for App Store / TestFlight). This halves the Rust compile time.
#
# IPHONEOS_DEPLOYMENT_TARGET must match ios/project.yml (deploymentTarget.iOS)
# and scripts/build-ios.sh's default. Xcode Cloud uses the value set in the
# workflow configuration in App Store Connect; the env var here is a safety
# fallback in case it is not propagated.
echo "==> Building Rust xcframework (device, ${CI_CONFIGURATION:-Debug})..."
IPHONEOS_DEPLOYMENT_TARGET="${IPHONEOS_DEPLOYMENT_TARGET:-16.0}" \
    ./scripts/build-ios.sh --device $RUST_PROFILE_FLAG

echo "==> ZedraFFI.xcframework contents:"
ls -lh ios/ZedraFFI.xcframework/ios-arm64/

echo "==> ci_pre_xcodebuild done."
