// Package main generates TypeScript types from Go contracts
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// contractsRelPath is the location of the generated TypeScript file
// relative to the module root.
const contractsRelPath = "frontend/src/types/contracts.ts"

// generateFileContent returns the full contents that should be written to
// contracts.ts (header + generated type definitions). Exposed so tests can
// verify the committed file matches the generator output and catch drift
// without writing to disk.
func generateFileContent() string {
	return fmt.Sprintf(`// Generated TypeScript types from Go contracts
// DO NOT EDIT - This file is auto-generated by cmd/generate-types

%s`, generateTypeDefinitions())
}

func main() {
	outputDir := filepath.Dir(contractsRelPath)
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		fmt.Printf("Error creating output directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(contractsRelPath, []byte(generateFileContent()), 0600); err != nil {
		fmt.Printf("Error writing TypeScript file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated TypeScript types: %s\n", contractsRelPath)
}

func generateTypeDefinitions() string {
	var sb strings.Builder

	// API Response wrapper
	sb.WriteString(`export interface APIResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
}

`)

	// Health constants - generated from internal/health/constants.go
	// These must stay in sync with the Go constants
	sb.WriteString(`// Health constants - generated from internal/health/constants.go
// Health levels
export const HealthLevelHealthy = 'healthy' as const;
export const HealthLevelDegraded = 'degraded' as const;
export const HealthLevelUnhealthy = 'unhealthy' as const;
export type HealthLevel = typeof HealthLevelHealthy | typeof HealthLevelDegraded | typeof HealthLevelUnhealthy;

// Admin states
export const AdminStateEnabled = 'enabled' as const;
export const AdminStateDisabled = 'disabled' as const;
export const AdminStateQuarantined = 'quarantined' as const;
export type AdminState = typeof AdminStateEnabled | typeof AdminStateDisabled | typeof AdminStateQuarantined;

// Health actions - suggested remediation for health issues
export const HealthActionNone = '' as const;
export const HealthActionLogin = 'login' as const;
export const HealthActionRestart = 'restart' as const;
export const HealthActionEnable = 'enable' as const;
export const HealthActionApprove = 'approve' as const;
export const HealthActionViewLogs = 'view_logs' as const;
export const HealthActionSetSecret = 'set_secret' as const;
export const HealthActionConfigure = 'configure' as const;
export type HealthAction =
  | typeof HealthActionNone
  | typeof HealthActionLogin
  | typeof HealthActionRestart
  | typeof HealthActionEnable
  | typeof HealthActionApprove
  | typeof HealthActionViewLogs
  | typeof HealthActionSetSecret
  | typeof HealthActionConfigure;

export interface HealthStatus {
  level: HealthLevel;
  admin_state: AdminState;
  summary: string;
  detail?: string;
  action?: HealthAction;
}

`)

	// Activity status vocabulary - generated from internal/storage/activity_models.go
	// (ValidActivityStatuses). Closed set: every consumer switches on it, so a new
	// status has to be added in Go and regenerated here.
	sb.WriteString(`// Activity status vocabulary - generated from internal/storage/activity_models.go
export const ActivityStatusSuccess = 'success' as const;
export const ActivityStatusError = 'error' as const;
export const ActivityStatusBlocked = 'blocked' as const;
/** Spec 093: shed by a concurrency limit before reaching the upstream. */
export const ActivityStatusRejected = 'rejected' as const;
export type ActivityStatusValue =
  | typeof ActivityStatusSuccess
  | typeof ActivityStatusError
  | typeof ActivityStatusBlocked
  | typeof ActivityStatusRejected;

/** Machine-readable cause of a spec-093 rejection (activity metadata rejection_reason). */
export type RejectionReason = 'queue_full' | 'queue_timeout';
/** Limiter tier that shed the call (activity metadata rejection_scope). */
export type RejectionScope = 'server' | 'global';

`)

	// Required-tools preflight (Spec 098) - generated from internal/contracts/types.go,
	// which mirrors internal/preflight/reasons.go (the single source of truth for
	// the taxonomy). A drift test in internal/preflight keeps the two identical.
	sb.WriteString(`// Preflight (Spec 098) - generated from internal/contracts/types.go
export const PreflightStatusReady = 'ready' as const;
export const PreflightStatusUnavailable = 'unavailable' as const;
export type PreflightStatus = typeof PreflightStatusReady | typeof PreflightStatusUnavailable;

/**
 * Closed 15-code failure enum. Additive-only: treat an unknown code as
 * non-retryable. 'server_saturated' is reserved and not emitted.
 */
export type PreflightReason =
  | 'server_initializing'
  | 'server_unhealthy'
  | 'server_disabled'
  | 'server_quarantined'
  | 'tool_pending_approval'
  | 'tool_changed'
  | 'tool_blocked_by_user'
  | 'oauth_required'
  | 'hash_mismatch'
  | 'server_not_in_scope'
  | 'tool_denied_by_config'
  | 'missing_annotation'
  | 'policy_filtered'
  | 'not_found'
  | 'server_not_configured';

/** Set-level aggregate (worst class present); drives the CLI exit code 0/10/11/12. */
export const PreflightVerdictReady = 'ready' as const;
export const PreflightVerdictDegradedRetryable = 'degraded_retryable' as const;
export const PreflightVerdictBlocked = 'blocked' as const;
export const PreflightVerdictUnknownIds = 'unknown_ids' as const;
export type PreflightVerdict =
  | typeof PreflightVerdictReady
  | typeof PreflightVerdictDegradedRetryable
  | typeof PreflightVerdictBlocked
  | typeof PreflightVerdictUnknownIds;

export interface PreflightToolRef {
  id: string;
  /** "sha256/v{N}:{hex}" - the schema version distinguishes a proxy hash bump from upstream drift. */
  pin_hash?: string;
}

export interface PreflightPolicy {
  read_only_only?: boolean;
  exclude_destructive?: boolean;
  exclude_open_world?: boolean;
}

export interface PreflightRequest {
  tools: PreflightToolRef[];
  profile?: string;
  policy?: PreflightPolicy;
  wait_ms?: number;
}

export interface PreflightToolResult {
  id: string;
  status: PreflightStatus;
  /** Present only when status is 'unavailable'. */
  reason?: PreflightReason;
  retryable?: boolean;
  /** Health-action vocabulary; omitted (not 'none') when the reason has no action. */
  action?: HealthAction;
  detail?: string;
  remediation?: string;
  /** Operator tier + ready results only; never disclosed to an agent token. */
  hash?: string;
  /** Up to 3 nearest caller-visible ids, on not_found only. */
  did_you_mean?: string[];
}

export interface PreflightResponse {
  verdict: PreflightVerdict;
  checked_at: string; // RFC3339
  waited_ms?: number;
  tools: PreflightToolResult[];
}

`)

	// Server types
	sb.WriteString(`export interface Server {
  id: string;
  name: string;
  url?: string;
  protocol: string;
  command?: string;
  args?: string[];
  working_dir?: string;
  env?: Record<string, string>;
  headers?: Record<string, string>;
  oauth?: OAuthConfig;
  enabled: boolean;
  quarantined: boolean;
  connected: boolean;
  connecting?: boolean; // Connection attempt in progress
  authenticated?: boolean; // Has stored OAuth token (regardless of validity)
  status: string;
  last_error?: string;
  connected_at?: string; // ISO date string
  last_reconnect_at?: string; // ISO date string
  reconnect_count: number;
  tool_count: number;
  tool_list_token_size?: number; // Token size for this server's tools
  created: string; // ISO date string
  updated: string; // ISO date string
  isolation?: IsolationConfig;
  isolation_defaults?: IsolationDefaults; // Resolved baseline values (read-only, used as placeholders)
  oauth_status?: 'authenticated' | 'expired' | 'error' | 'none'; // OAuth authentication status
  token_expires_at?: string; // ISO date string when OAuth token expires
  user_logged_out?: boolean; // True if user explicitly logged out (prevents auto-reconnection)
  health?: HealthStatus; // Unified health status calculated by the backend
  trust_mode?: string; // Per-server approval trust mode (spec 086): 'auto' | 'scan' | 'manual'; raw configured value, absent when unset (effective default: manual)
  expose_prompts?: boolean; // F9 per-server prompt-aggregation override; absent = inherit default aggregation, false = exclude this server's prompts
  security_scan?: SecurityScanSummary; // Latest scan summary (spec 086); ABSENT when no scan has ever run
  // Spec 093 (#955) per-server concurrency overrides. Tri-state: absent =
  // inherit server_concurrency_defaults, 0 = disabled for this server,
  // positive = override. Effective concurrency is additionally bounded by the
  // proxy-wide (global) limiter.
  max_concurrent_requests?: number;
  queue_size?: number;
  queue_timeout?: string; // Go duration string, e.g. '30s'
}

export interface SecurityScanSummary {
  last_scan_at?: string; // ISO date string
  risk_score: number; // 0-100
  status: string; // 'clean' | 'warnings' | 'dangerous' | 'failed' | 'scanning' (absence of the whole summary = never scanned)
  finding_counts?: FindingCounts;
  scanners_run: number;
  scanners_failed: number;
  scanners_total: number;
  deep_scan?: DeepScanDescriptor; // Opt-in deep-scan layer status; never influences status
}

export interface FindingCounts {
  dangerous: number;
  warning: number;
  info: number;
  total: number;
}

export interface DeepScanDescriptor {
  enabled: boolean;
  ran: boolean;
  available: boolean;
  scanners_failed?: { id: string; reason: string }[];
  skipped_scanners?: string[]; // Docker scanners enabled but skipped while deep scan is off
}

export interface OAuthConfig {
  auth_url?: string;
  token_url?: string;
  client_id: string;
  scopes?: string[];
  extra_params?: Record<string, string>;
  redirect_port?: number;
}

export interface IsolationConfig {
  enabled: boolean;
  image?: string;
  network_mode?: string;
  extra_args?: string[];
  memory_limit?: string;
  cpu_limit?: string;
  working_dir?: string;
  timeout?: string;
}

// IsolationDefaults reports the resolved baseline Docker isolation
// values the backend will apply when no per-server override is set.
// Populated on server-list / server-get responses; the Web UI uses these
// as placeholders so "empty = inherit" is discoverable instead of
// mysterious. Never sent back on PATCH requests.
export interface IsolationDefaults {
  runtime_type?: string;
  image?: string;
  network_mode?: string;
  extra_args?: string[];
  working_dir?: string;
}

`)

	// Tool types
	sb.WriteString(`export interface Tool {
  name: string;
  server_name: string;
  description: string;
  schema?: Record<string, any>;
  usage: number;
  last_used?: string; // ISO date string
  // Mirrors contracts.Tool.Disabled on the Go side — present when an
  // approval record exists for this tool. Absent means "enabled" (default).
  disabled?: boolean;
  // Tool-level quarantine status surfaced by the same approval record.
  // Optional because non-quarantined tools simply omit the field.
  approval_status?: string;
  // Why the trust_mode: scan gate held this tool for review (spec 086
  // FR-018). held_signals names the matched deterministic check ids, e.g.
  // "tpa.TPA-2026-0001.hidden_instruction". All three are absent unless the
  // tool is currently held by the scan gate.
  held_reason?: string;
  held_verdict?: string;
  held_signals?: string[];
  // The tool's current hash in the preflight pin format "sha256/v{N}:{hex}"
  // (spec 098 FR-011) — the value to paste into a preflight pin. Operator tier
  // only: absent for agent-token callers and for tools with no stored hash.
  hash?: string;
}

export interface SearchResult {
  tool: Tool;
  score: number;
  snippet?: string;
  matches: number;
}

`)

	// Statistics and status
	sb.WriteString(`export interface ServerStats {
  total_servers: number;
  connected_servers: number;
  quarantined_servers: number;
  total_tools: number;
  docker_containers: number;
}

export interface LogEntry {
  timestamp: string; // ISO date string
  level: string;
  message: string;
  server?: string;
  fields?: Record<string, any>;
}

export interface SystemStatus {
  phase: string;
  message: string;
  uptime: number; // duration in nanoseconds
  started_at: string; // ISO date string
  config_path: string;
  log_dir: string;
  runtime: RuntimeStatus;
  servers: ServerStats;
}

export interface RuntimeStatus {
  version: string;
  go_version: string;
  build_time?: string;
  index_status: string;
  storage_status: string;
  last_config_load: string; // ISO date string
}

`)

	// Request/Response DTOs
	sb.WriteString(`export interface ToolCallRequest {
  tool_name: string;
  args: Record<string, any>;
}

export interface ToolCallResponse {
  tool_name: string;
  server_name: string;
  result: any;
  error?: string;
  duration: string;
  timestamp: string; // ISO date string
}

export interface Event {
  type: string;
  data: any;
  server?: string;
  timestamp: string; // ISO date string
  metadata?: Record<string, any>;
}

`)

	// Secret types
	sb.WriteString(`// Secret Management Types
export interface Ref {
  type: string;      // env, keyring, op, age
  name: string;      // environment variable name, keyring alias, etc.
  original: string;  // original reference string
}

export interface EnvVarStatus {
  secret_ref: Ref;
  is_set: boolean;
}

export interface ConfigSecretsResponse {
  secrets: Ref[];
  environment_vars: EnvVarStatus[];
  total_secrets: number;
  total_env_vars: number;
}

export interface MigrationCandidate {
  field: string;      // Field path in configuration
  value: string;      // Masked value for display
  suggested: string;  // Suggested secret reference
  confidence: number; // Confidence score (0.0 to 1.0)
  migrating?: boolean; // UI state for migration in progress
}

export interface MigrationAnalysis {
  candidates: MigrationCandidate[];
  total_found: number;
}

`)

	// API Response DTOs
	sb.WriteString(`// API Response DTOs
export interface GetServersResponse {
  servers: Server[];
  stats: ServerStats;
}

export interface GetServerToolsResponse {
  server_name: string;
  tools: Tool[];
  count: number;
}

export interface SearchToolsResponse {
  query: string;
  results: SearchResult[];
  total: number;
  took: string;
}

export interface GetServerLogsResponse {
  server_name: string;
  logs: LogEntry[];
  count: number;
}

export interface ServerActionResponse {
  server: string;
  action: string;
  success: boolean;
  async?: boolean;
}

export interface QuarantinedServersResponse {
  servers: Server[];
  count: number;
}

`)

	// API client helper types
	sb.WriteString(`// API Client Helper Types
export type ServerAction = 'enable' | 'disable' | 'restart' | 'login';

export interface ServerToggleRequest {
  server: string;
  action: ServerAction;
}

export interface SearchRequest {
  query: string;
  limit?: number;
}

export interface LogsRequest {
  server: string;
  tail?: number;
}

// SSE Event Types
export type SSEEventType =
  | 'status'
  | 'servers.changed'
  | 'server.connected'
  | 'server.disconnected'
  | 'config.reloaded'
  | 'tools.indexed';

export interface SSEEvent {
  type: SSEEventType;
  data: any;
  timestamp: number; // Unix timestamp
}

// Error types for better error handling
export interface APIError {
  success: false;
  error: string;
}

export interface APISuccess<T> {
  success: true;
  data: T;
}

export type APIResult<T> = APISuccess<T> | APIError;

// Type guards
export function isAPIError(response: APIResponse): response is APIError {
  return !response.success;
}

export function isAPISuccess<T>(response: APIResponse<T>): response is APISuccess<T> {
  return response.success;
}

// Update check types (from internal/updatecheck/types.go)
export interface UpdateInfo {
  available: boolean;
  latest_version?: string;
  release_url?: string;
  checked_at?: string; // ISO date string
  is_prerelease?: boolean;
  check_error?: string;
  // Spec 079 US2 (additive per FR-021): detected install channel (homebrew,
  // dmg, deb, rpm, docker, go-install, windows-installer, tarball, unknown).
  install_channel?: string;
  // One-line update command for the channel; only present when an update is
  // available and the channel has a safe command (FR-009).
  update_command?: string;
  // Spec 079 US3 (FR-019): the core runs in a CI / non-interactive context —
  // UI surfaces must stay quiet while the facts remain machine-readable.
  nudges_suppressed?: boolean;
}

export interface InfoResponse {
  version: string;
  web_ui_url: string;
  listen_addr: string;
  endpoints: {
    http: string;
    socket: string;
  };
  update?: UpdateInfo;
  // Spec 092 FR-001a: durable launch provenance of the running core —
  // "tray", "installer", or "" (user-launched / unknown).
  launched_by: string;
  // Spec 092 FR-002: OS process id of the running core, so a tray that only
  // attached to it still has a mechanism to stop a stale one.
  pid: number;
  // Spec 092 FR-015: effective update policy. Always present — the optional
  // "update" object above is absent both when checking is disabled and when
  // no check has run yet, so it cannot be used to infer permission.
  update_policy: UpdatePolicy;
}

// Spec 092 FR-015: the effective, hot-reloadable update policy.
export interface UpdatePolicy {
  // Automatic checks allowed? (update_check.enabled, overridden by
  // MCPPROXY_DISABLE_AUTO_UPDATE=true). A user-initiated check stays allowed.
  enabled: boolean;
  // Tracked release channel: "stable" or "rc".
  channel: string;
  // UI surfaces must stay quiet (CI / non-interactive context).
  nudges_suppressed: boolean;
}
`)

	return sb.String()
}
