[build]
incremental = true
jobs = 16
rustc-wrapper = "sccache"

[env]
CMAKE_POLICY_VERSION_MINIMUM = "3.5"
PCRE2_SYS_STATIC = "1"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C", "target-cpu=native",
  "-C", "target-feature=+crt-static",
  "-C", "link-arg=-fuse-ld=mold",
  "-C", "link-arg=-Wl,--no-rosegment",
]

[profile.dev]
opt-level = 1
debug = "line-tables-only"
incremental = true
codegen-units = 256
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 2

[profile.local]
inherits = "dev"
opt-level = 1
debug = "line-tables-only"
incremental = true
codegen-units = 256
split-debuginfo = "unpacked"
lto = false

[profile.release]
lto = false
codegen-units = 16
split-debuginfo = "unpacked"
strip = false

[profile.ci]
inherits = "release"
lto = false
strip = true
debug = false
