processes:
  prometheus:
    command: prometheus --config.file=./prometheus.yml --storage.tsdb.path=./.prometheus
      --web.listen-address=0.0.0.0:${PROMETHEUS_PORT}
    working_dir: .
    log_location: .state/logs/prometheus.log
