import sys

M = "/tmp/benchlink-kb/tools/sovereign-router/sovereign-router-ts/router_matrix.ts"
R = "/tmp/benchlink-kb/tools/sovereign-router/sovereign-router-ts/router.ts"

with open(M) as f:
    src = f.read()

# 1. prior tracking fields after the elo map declaration
old_fields = "  elo = new Map<string, number>();\n"
new_fields = (
    "  elo = new Map<string, number>();\n"
    "  /** Bench-derived Elo priors: last applied prior per provider, so\n"
    "   *  hot-reload only re-seeds providers untouched by live traffic. */\n"
    "  priorElo = new Map<string, number>();\n"
    "  priorsMtime = 0;\n"
    "  priorsSource = \"\";\n"
)
assert src.count(old_fields) == 1, "fields anchor"
src = src.replace(old_fields, new_fields)

# 2. module-level bench-prior loader after the node:fs import
old_import = 'import * as fs from "node:fs";\n'
loader = '''import * as fs from "node:fs";

// ---------------------------------------------------------------------------
// Bench priors (bench-priors.json) -- bench-derived Elo seeds.
//
// Generated by gen-bench-priors.py from real measured data: GuideLLM v3
// deterministic quality, MODEL-MAX liveness/latency, router-proof
// availability. Read at startup and on hot-reload (/admin/reload, SIGHUP);
// providers whose Elo has moved via live traffic keep their learned values.
// Missing or corrupt file fails open to flat 1000 (today's behavior).
// ---------------------------------------------------------------------------
const PRIORS_PATH = `${import.meta.dir}/bench-priors.json`;

function loadBenchPriors(): {
  priors: Record<string, number>;
  source: string;
  mtime: number;
} {
  try {
    const st = fs.statSync(PRIORS_PATH);
    const doc = JSON.parse(fs.readFileSync(PRIORS_PATH, "utf8"));
    const priors: Record<string, number> = {};
    for (const [p, pr] of Object.entries(doc.priors || {})) {
      const elo = (pr as { elo?: number }).elo;
      if (typeof elo === "number" && Number.isFinite(elo)) priors[p] = elo;
    }
    return { priors, source: doc.generated_ts || "unknown", mtime: st.mtimeMs };
  } catch {
    return { priors: {}, source: "missing", mtime: 0 };
  }
}
'''
assert src.count(old_import) == 1, "import anchor"
src = src.replace(old_import, loader)

# 3. constructor: seed from bench priors instead of flat 1000
old_ctor = """  constructor() {
    for (const p of Object.keys(PROVIDERS)) {
      this.elo.set(p, 1000);
      this.circuit.set(p, "closed");
    }
"""
new_ctor = """  constructor() {
    for (const p of Object.keys(PROVIDERS)) {
      this.circuit.set(p, "closed");
    }
    const seeded = this.applyBenchPriors(true);
    console.log(
      `[sovereign-router] bench priors: source=${seeded.source} ` +
        `seeded=${seeded.reseeded.join(",")}`,
    );
"""
assert src.count(old_ctor) == 1, "ctor anchor"
src = src.replace(old_ctor, new_ctor)

# 4. applyBenchPriors method before record(
old_record = "  record(\n    model: string,\n"
method = '''  /**
   * applyBenchPriors -- seed Elo from bench-priors.json.
   *
   * Startup (force=true): every provider gets its bench prior (1000 when
   * unbenched or the file is missing).
   * Hot-reload: only providers whose Elo is still exactly at the last
   * applied prior are re-seeded -- providers with live traffic history keep
   * their learned Elo. Live outcomes keep updating Elo either way.
   */
  applyBenchPriors(force = false): {
    reloaded: boolean;
    reseeded: string[];
    source: string;
  } {
    const { priors, source, mtime } = loadBenchPriors();
    if (!force && mtime === this.priorsMtime) {
      return { reloaded: false, reseeded: [], source: this.priorsSource };
    }
    const reseeded: string[] = [];
    for (const p of Object.keys(PROVIDERS)) {
      const prior = priors[p] ?? 1000;
      const cur = this.elo.get(p) ?? 1000;
      const last = this.priorElo.get(p) ?? 1000;
      if (force || cur === last) {
        this.elo.set(p, prior);
        this.priorElo.set(p, prior);
        reseeded.push(p);
      }
    }
    this.priorsMtime = mtime;
    this.priorsSource = source;
    return { reloaded: true, reseeded, source };
  }

'''
assert src.count(old_record) == 1, "record anchor"
src = src.replace(old_record, method + old_record)

with open(M, "w") as f:
    f.write(src)
print("router_matrix.ts patched")

# 5. hook hotReload in router.ts (single hook point: the function itself,
#    which serves both /admin/reload and SIGHUP)
with open(R) as f:
    rsrc = f.read()

old_fn = """  refreshLiveModels().catch((e) => log("post-reload live refresh failed:", e));
  return { source, keys };"""
new_fn = """  refreshLiveModels().catch((e) => log("post-reload live refresh failed:", e));
  const priors = state.applyBenchPriors();
  log(`hot reload (${source}): priors=${JSON.stringify(priors)}`);
  return { source, keys, priors };"""
assert rsrc.count(old_fn) == 1, "hotreload fn anchor"
rsrc = rsrc.replace(old_fn, new_fn)

with open(R, "w") as f:
    f.write(rsrc)
print("router.ts patched")
