import { HealthDB } from "./router_health.ts";
import {
  DB_PATH,
  STICKY_TTL,
  PROVIDERS,
  nvidiaKeys,
  QUARANTINE_BASE_S,
  QUARANTINE_MAX_S,
  QUARANTINE_PROBE_MS,
} from "./router_config.ts";
import * as fs from "node:fs";

// ---------------------------------------------------------------------------
// Bench priors (bench-priors.json) -- bench-derived Elo seeds.
//
// Generated by gen-bench-priors.py from real measured data: GuideLLM v3
// deterministic quality, MODEL-MAX liveness/latency, router-proof
// availability. Read at startup and on hot-reload (/admin/reload, SIGHUP);
// providers whose Elo has moved via live traffic keep their learned values.
// Missing or corrupt file fails open to flat 1000 (today's behavior).
// ---------------------------------------------------------------------------
const PRIORS_PATH = `${import.meta.dir}/bench-priors.json`;

function loadBenchPriors(): {
  priors: Record<string, number>;
  source: string;
  mtime: number;
} {
  try {
    const st = fs.statSync(PRIORS_PATH);
    const doc = JSON.parse(fs.readFileSync(PRIORS_PATH, "utf8"));
    const priors: Record<string, number> = {};
    for (const [p, pr] of Object.entries(doc.priors || {})) {
      const elo = (pr as { elo?: number }).elo;
      if (typeof elo === "number" && Number.isFinite(elo)) priors[p] = elo;
    }
    return { priors, source: doc.generated_ts || "unknown", mtime: st.mtimeMs };
  } catch {
    return { priors: {}, source: "missing", mtime: 0 };
  }
}

// ---------------------------------------------------------------------------
// Model-pressure governor (ported from flock proxy/src/governor.rs).
//
// NIM's serving stack has a per-model worker-concurrency cap orthogonal to
// the per-key RPM limit ("ResourceExhausted: Worker local total request
// limit reached (32/32)"). It is model-scoped and shared across all keys, so
// failing over to another key can't help — worker exhaustion backs off the
// *model* instead of cooling down the lane that carried it:
//
// - Every model starts ungoverned (no cap, zero config).
// - On a worker-exhaustion error the governor engages at half the observed
//   in-flight count, and briefly blocks new admissions (2s drain gap) while
//   workers free up as generations finish.
// - Additive increase: +1 concurrency per stable minute; dissolves back to
//   ungoverned after 30 clean minutes. The worker pool is shared infra, so
//   the real ceiling moves with other tenants' load — a static cap would be
//   wrong in both directions.
// - An operator override pins a fixed cap for a model (no adaptation).
//
// Keyed by "provider/model" (flock was NVIDIA-only and keyed by model name).
// ---------------------------------------------------------------------------

/// The worker-exhaustion signature in an upstream error body. Must be
/// checked *before* generic retry handling: this failure is model-scoped,
/// never a reason to cool down the lane that carried it.
export function isWorkerExhausted(body: string): boolean {
  return body.includes("Worker local total request limit");
}

export interface GovernorModelState {
  limit: number; // 0 = ungoverned
  inflight: number;
  blockedUntil: number; // epoch seconds; 0 = not blocked
  lastExhausted: number; // epoch seconds; 0 = never
  lastAdjusted: number; // epoch seconds; 0 = never
  exhaustedTotal: number; // lifetime counter (metrics)
}

interface GovernorSnapshotFile {
  models: Record<
    string,
    {
      limit: number;
      lastExhausted: number;
      lastAdjusted: number;
      blockedUntil: number;
      exhaustedTotal: number;
    }
  >;
}

/// A held admission: the request is (about to be) in flight on this model.
/// Call release() on every exit path (try/finally) — it is idempotent.
export class ModelPermit {
  private released = false;
  constructor(
    private gov: Governor,
    readonly key: string,
  ) {}
  release(): void {
    if (!this.released) {
      this.released = true;
      this.gov.release(this.key);
    }
  }
}

export class Governor {
  static readonly EXHAUST_BACKOFF_S = 2;
  static readonly GROW_INTERVAL_S = 60;
  static readonly DISSOLVE_AFTER_S = 30 * 60;
  private static readonly SAVE_DEBOUNCE_S = 5;

  private models = new Map<string, GovernorModelState>();
  /** Operator-pinned caps (key -> limit); pinned models skip adaptation. */
  overrides = new Map<string, number>();
  private persistPath: string | null;
  private lastSave = 0;
  private dirty = false;

  constructor(persistPath: string | null = null) {
    this.persistPath = persistPath;
    this.restore();
  }

  private st(key: string): GovernorModelState {
    let s = this.models.get(key);
    if (!s) {
      s = {
        limit: 0,
        inflight: 0,
        blockedUntil: 0,
        lastExhausted: 0,
        lastAdjusted: 0,
        exhaustedTotal: 0,
      };
      this.models.set(key, s);
    }
    return s;
  }

  /** Try to admit a request on `key`; null when at cap / in drain gap. */
  admit(key: string, nowS = Date.now() / 1000): ModelPermit | null {
    const s = this.st(key);
    // Adaptive lifecycle (skipped for operator-pinned models): dissolve
    // after a long clean period, else grow one per stable minute. Lazy —
    // evaluated under demand, which is the only time the cap matters.
    if (!this.overrides.has(key) && s.limit > 0) {
      if (
        s.lastExhausted > 0 &&
        nowS - s.lastExhausted >= Governor.DISSOLVE_AFTER_S
      ) {
        s.limit = 0;
        s.lastAdjusted = nowS;
        this.markDirty();
      } else if (
        s.lastAdjusted > 0 &&
        nowS - s.lastAdjusted >= Governor.GROW_INTERVAL_S
      ) {
        s.limit += 1;
        s.lastAdjusted = nowS;
        this.markDirty();
      }
    }
    if (s.blockedUntil > nowS) return null;
    const limit = this.overrides.get(key) ?? s.limit;
    if (limit > 0 && s.inflight >= limit) return null;
    s.inflight += 1;
    return new ModelPermit(this, key);
  }

  release(key: string): void {
    const s = this.models.get(key);
    if (s) s.inflight = Math.max(0, s.inflight - 1);
  }

  /**
   * Record a worker-exhaustion error on `key`. Call while the failing
   * request's permit is still held, so the observed in-flight count
   * includes it. Engages (or tightens) the cap at half that count and
   * opens a short drain gap; operator-pinned models only get the gap.
   */
  noteExhausted(key: string, nowS = Date.now() / 1000): void {
    const s = this.st(key);
    s.exhaustedTotal += 1;
    s.blockedUntil = nowS + Governor.EXHAUST_BACKOFF_S;
    s.lastExhausted = nowS;
    if (!this.overrides.has(key)) {
      s.limit = Math.max(1, Math.floor(s.inflight / 2));
      s.lastAdjusted = nowS;
    }
    this.markDirty();
  }

  /** Governed-model entries for metrics: [key, state]. */
  entries(): [string, GovernorModelState][] {
    return [...this.models.entries()];
  }

  // -- persistence: write-behind JSON, wall-clock seconds ------------------
  private markDirty(): void {
    this.dirty = true;
    if (Date.now() / 1000 - this.lastSave >= Governor.SAVE_DEBOUNCE_S)
      this.save();
  }

  /** Flush a pending snapshot now (also used by tests). */
  save(): void {
    if (!this.persistPath || !this.dirty) return;
    try {
      const models: GovernorSnapshotFile["models"] = {};
      for (const [k, s] of this.models) {
        if (s.limit <= 0 && s.exhaustedTotal <= 0) continue;
        models[k] = {
          limit: s.limit,
          lastExhausted: s.lastExhausted,
          lastAdjusted: s.lastAdjusted,
          blockedUntil: s.blockedUntil,
          exhaustedTotal: s.exhaustedTotal,
        };
      }
      fs.writeFileSync(this.persistPath, JSON.stringify({ models }, null, 1));
      this.lastSave = Date.now() / 1000;
      this.dirty = false;
    } catch {
      /* persistence is best-effort; admission semantics are untouched */
    }
  }

  private restore(): void {
    if (!this.persistPath) return;
    try {
      const raw = fs.readFileSync(this.persistPath, "utf8");
      const snap = JSON.parse(raw) as GovernorSnapshotFile;
      const nowS = Date.now() / 1000;
      for (const [k, m] of Object.entries(snap.models || {})) {
        if (!m || m.limit <= 0) continue;
        const s = this.st(k);
        s.limit = m.limit;
        s.lastExhausted = m.lastExhausted || 0;
        s.lastAdjusted = m.lastAdjusted || 0;
        // Elapsed drain gaps are not resurrected; pacing is, so the AIMD
        // lifecycle continues where it left off.
        s.blockedUntil = m.blockedUntil > nowS ? m.blockedUntil : 0;
        s.exhaustedTotal = m.exhaustedTotal || 0;
        // inflight restarts at 0 — in-flight requests didn't survive reboot.
      }
    } catch {
      /* no snapshot yet — start clean */
    }
  }
}

// ---------------------------------------------------------------------------
// Matrix state
// ---------------------------------------------------------------------------
export class Matrix {
  fail = new Map<string, [number, number]>();
  elo = new Map<string, number>();
  /** Bench-derived Elo priors: last applied prior per provider, so
   *  hot-reload only re-seeds providers untouched by live traffic. */
  priorElo = new Map<string, number>();
  priorsMtime = 0;
  priorsSource = "";
  /**
   * Providers with a durably persisted Elo row: restored at startup or
   * written by a live update through setElo(). Hot-reload NEVER re-seeds
   * these -- even when the persisted value numerically equals the bench
   * prior. Numeric equality is not proof a provider is untouched.
   */
  persistedEloProviders = new Set<string>();
  circuit = new Map<string, string>();
  circuitOpenUntil = new Map<string, number>();
  // --- v3.2 exponential-backoff quarantine ---
  // quarantineLevel: consecutive circuit openings without a success.
  // lastError: most recent failure signature per provider (for /status).
  quarantineLevel = new Map<string, number>();
  /** EMA of successful completion latency (ms) — HFT: ordering input. */
  emaLat = new Map<string, number>();
  lastError = new Map<string, { status: number; err: string; at: number }>();
  /**
   * entitlementDead — per-model fail-fast bench (503-forensics 2026-09-21).
   *
   * A 404 on a model attempt means "no such model for this key" — the ID is
   * delisted or we're not entitled, and NEITHER heals by retrying (measured:
   * tencent/hy3:free 404'd 7x in 15 min, each attempt pure burn at ~130ms).
   * So the model is benched for the process lifetime after ONE 404: no
   * retry burn, and the race sets skip it (see firstUsableModelFor /
   * freeCandidates / callOne guard). Only an NVIDIA-side relist (or a
   * daemon restart) re-admits it. Distinct from transient 404/429 by
   * construction: 429s never bench, and provider-level 404s (endpoint
   * misconfig) don't flow through record().
   */
  entitlementDead = new Map<string, number>();
  fifoDepth = 0;
  health: HealthDB;
  governor: Governor;

  // --- Flap tracker: models that repeatedly return empty (non-substantive)
  // completions collect strikes; FLAP_STRIKES within FLAP_WINDOW_S benches
  // the model out of candidate pools until the strikes decay. Re-entry is
  // automatic — the next race after decay re-probes the model for real.
  emptyStrikes = new Map<string, { n: number; last: number }>();
  static readonly FLAP_STRIKES = 3;
  static readonly FLAP_WINDOW_S = 600;

  recordEmpty(prov: string, model: string): void {
    const k = `${prov}/${model}`;
    const now = Date.now() / 1000;
    const cur = this.emptyStrikes.get(k);
    if (!cur || now - cur.last > Matrix.FLAP_WINDOW_S) {
      this.emptyStrikes.set(k, { n: 1, last: now });
    } else {
      this.emptyStrikes.set(k, { n: cur.n + 1, last: now });
    }
  }

  emptyStrikeCount(prov: string, model: string): number {
    const k = `${prov}/${model}`;
    const cur = this.emptyStrikes.get(k);
    if (!cur) return 0;
    if (Date.now() / 1000 - cur.last > Matrix.FLAP_WINDOW_S) {
      this.emptyStrikes.delete(k);
      return 0;
    }
    return cur.n;
  }

  flapBanned(prov: string, model: string): boolean {
    return this.emptyStrikeCount(prov, model) >= Matrix.FLAP_STRIKES;
  }

  // --- NVIDIA multi-key rotation (absorbed from the retired :8000 proxy):
  // round-robin across the nvapi key pool, each key behind its own token
  // bucket (NVIDIA_RPM per minute). Returns null when every bucket is dry.
  nvidiaIdx = 0;
  nvidiaBuckets = new Map<string, { tokens: number; last: number }>();
  static readonly NVIDIA_RPM = 40;

  nextNvidiaKey(): string | null {
    const keys = nvidiaKeys();
    if (!keys.length) return null;
    const now = Date.now() / 1000;
    for (let i = 0; i < keys.length; i++) {
      const k = keys[(this.nvidiaIdx + i) % keys.length];
      let b = this.nvidiaBuckets.get(k);
      if (!b) {
        b = { tokens: Matrix.NVIDIA_RPM, last: now };
        this.nvidiaBuckets.set(k, b);
      }
      const elapsed = now - b.last;
      if (elapsed > 0) {
        b.tokens = Math.min(
          Matrix.NVIDIA_RPM,
          b.tokens + (elapsed * Matrix.NVIDIA_RPM) / 60,
        );
        b.last = now;
      }
      if (b.tokens >= 1) {
        b.tokens -= 1;
        this.nvidiaIdx = (this.nvidiaIdx + i + 1) % keys.length;
        return k;
      }
    }
    return null;
  }

  constructor(dbPath: string = DB_PATH) {
    for (const p of Object.keys(PROVIDERS)) {
      this.circuit.set(p, "closed");
    }
    // HealthDB first: Elo restore reads persisted live-learned values from
    // it; bench priors only fill providers with no stored row.
    // Fail open: a corrupt/unopenable DB must never take the router down --
    // fall back to an in-memory DB and keep routing on priors.
    try {
      this.health = new HealthDB(dbPath);
    } catch (e) {
      console.error(
        `[sovereign-router] HealthDB unavailable at ${dbPath}, ` +
          `Elo persistence disabled (routing on priors):`,
        e,
      );
      this.health = new HealthDB(":memory:");
    }
    const seeded = this.applyBenchPriors(true);
    console.log(
      `[sovereign-router] bench priors: source=${seeded.source} ` +
        `seeded=${seeded.reseeded.join(",")}` +
        (seeded.restored.length
          ? ` restored=${seeded.restored.join(",")}`
          : ""),
    );
    this.governor = new Governor(dbPath + ".governor.json");
  }

  /**
   * setElo — the ONLY writer of provider Elo. Updates the in-memory map and
   * writes through to the HealthDB (elo_state table) so the value survives
   * a daemon restart. Best-effort: a DB failure must never break routing
   * (same contract as the Governor's snapshot persistence).
   *
   * markPersisted=true (default): the provider joins persistedEloProviders.
   * Use for live-learned values and startup restores. Hot-reload re-seeds a
   * bench prior with markPersisted=false: the refreshed baseline is written,
   * but a later priors refresh may still update it -- it is a baseline, not
   * learned state.
   */
  private setElo(prov: string, value: number, markPersisted = true): void {
    this.elo.set(prov, value);
    if (markPersisted) this.persistedEloProviders.add(prov);
    try {
      this.health.saveElo(prov, value);
    } catch {
      /* persistence is best-effort; routing semantics are untouched */
    }
  }

  /**
   * applyBenchPriors -- seed Elo from bench-priors.json.
   *
   * Startup (force=true): providers with a persisted Elo row in the
   * HealthDB get their live-learned value back and join
   * persistedEloProviders -- priors never clobber a restore, even on exact
   * numeric equality with the prior. Providers with no stored row fall back
   * to the bench prior (1000 when unbenched or the file is missing) IN
   * MEMORY ONLY: initial bench seeding is a fallback, not learned state,
   * and is never persisted. Only live outcome changes (via setElo) create
   * elo_state rows.
   * Hot-reload: re-seeds only providers that are neither durably persisted
   * nor touched by live traffic. persistedEloProviders is the authority, so
   * a restored value that happens to equal the old prior stays protected.
   * Live outcomes keep updating Elo either way.
   */
  applyBenchPriors(force = false): {
    reloaded: boolean;
    reseeded: string[];
    restored: string[];
    source: string;
  } {
    const { priors, source, mtime } = loadBenchPriors();
    if (!force && mtime === this.priorsMtime) {
      return {
        reloaded: false,
        reseeded: [],
        restored: [],
        source: this.priorsSource,
      };
    }
    let stored: Record<string, number> = {};
    if (force) {
      try {
        stored = this.health.loadElo();
      } catch {
        /* corrupt/empty table — priors are the fallback */
      }
    }
    const reseeded: string[] = [];
    const restored: string[] = [];
    for (const p of Object.keys(PROVIDERS)) {
      const prior = priors[p] ?? 1000;
      if (force) {
        const prev = stored[p];
        if (typeof prev === "number") {
          // Restored live-learned Elo: map-only (already in the DB), and
          // marked persisted so hot-reload never re-seeds it -- even when
          // the stored value numerically equals the bench prior.
          this.elo.set(p, prev);
          this.priorElo.set(p, prior);
          this.persistedEloProviders.add(p);
          restored.push(p);
        } else {
          // Missing row: bench prior fills the in-memory map ONLY. Never
          // persisted -- fallback priors are not learned state.
          this.elo.set(p, prior);
          this.priorElo.set(p, prior);
          reseeded.push(p);
        }
      } else {
        // Durably persisted providers are never re-seeded, regardless of
        // numeric equality with the prior.
        if (this.persistedEloProviders.has(p)) continue;
        const cur = this.elo.get(p) ?? 1000;
        const last = this.priorElo.get(p) ?? 1000;
        if (cur === last) {
          // Untouched by live traffic: refresh the baseline. Written to the
          // DB but NOT marked persisted -- a later priors refresh may update
          // it again; only learned values are protected.
          this.setElo(p, prior, false);
          this.priorElo.set(p, prior);
          reseeded.push(p);
        }
      }
    }
    this.priorsMtime = mtime;
    this.priorsSource = source;
    return { reloaded: true, reseeded, restored, source };
  }

  record(
    model: string,
    prov: string,
    status: number,
    lat: number,
    winner = 0,
    strategy = "",
    session = "",
    estTokens = 0,
  ): void {
    const latMs = lat * 1000;
    this.health.recordRequest(
      prov,
      model,
      status,
      latMs,
      strategy,
      winner,
      session,
      estTokens,
    );
    if (status === 200) {
      const old = this.circuit.get(prov) || "closed";
      this.setElo(prov, (this.elo.get(prov) || 1000) + 16);
      // Latency EMA: alpha 0.2 — recent completions steer ordering.
      const prev = this.emaLat.get(prov) ?? latMs;
      this.emaLat.set(prov, prev * 0.8 + latMs * 0.2);
      this.fail.set(prov, [0, Date.now() / 1000]);
      this.circuit.set(prov, "closed");
      this.quarantineLevel.set(prov, 0);
      if (old !== "closed") {
        this.health.recordHealing(
          prov,
          model,
          "circuit_recovered",
          old,
          "closed",
        );
      }
    } else if (status === 429) {
      this.health.recordRateLimit(prov, model, status);
      this.setElo(prov, Math.max(100, (this.elo.get(prov) || 1000) - 8));
      const [c] = this.fail.get(prov) || [0, 0];
      this.fail.set(prov, [c + 1, Date.now() / 1000]);
    } else {
      // 503-forensics 2026-09-21: failure-class-aware counting.
      // - 401/402 (dead key): the PROVIDER is dead — count 3x so the
      //   circuit opens and laneDead excludes it after a single attempt.
      // - 404 (delisted / not-entitled model id): the MODEL is dead —
      //   bench it permanently (fail-fast, zero retry burn); the provider
      //   keeps serving its healthy models, so normal +1 counting here.
      // - 5xx/timeouts: transient until proven otherwise (+1).
      if (status === 404) this.noteEntitlement404(prov, model);
      const step = status === 401 || status === 402 ? 3 : 1;
      const [c] = this.fail.get(prov) || [0, 0];
      this.fail.set(prov, [c + step, Date.now() / 1000]);
      this.setElo(prov, Math.max(100, (this.elo.get(prov) || 1000) - 32));
      if (c + step >= 3) {
        const old = this.circuit.get(prov) || "closed";
        // Exponential backoff: BASE * 2^(level-1), capped at MAX.
        const level = (this.quarantineLevel.get(prov) || 0) + 1;
        this.quarantineLevel.set(prov, level);
        const backoff = Math.min(
          QUARANTINE_BASE_S * 2 ** (level - 1),
          QUARANTINE_MAX_S,
        );
        this.circuit.set(prov, "open");
        this.circuitOpenUntil.set(prov, Date.now() / 1000 + backoff);
        this.health.recordHealing(
          prov,
          model,
          "circuit_opened",
          old,
          "open",
          `${c + step} consecutive failures (step ${step}); quarantine level ${level}, backoff ${backoff}s`,
        );
      }
    }
  }

  stickyGet(sid: string) {
    return this.health.stickyGet(sid, STICKY_TTL);
  }
  stickySet(sid: string, p: string, m: string) {
    this.health.stickySet(sid, p, m);
  }

  /** Record a failure signature for /status (call on every failed attempt). */
  noteError(prov: string, status: number, err: string): void {
    this.lastError.set(prov, {
      status,
      err: String(err).slice(0, 300),
      at: Date.now() / 1000,
    });
  }

  consecutiveFailures(p: string): number {
    return this.fail.get(p)?.[0] || 0;
  }

  /** EMA of successful completion latency in ms, or null if never measured. */
  latencyEmaMs(p: string): number | null {
    return this.emaLat.get(p) ?? null;
  }

  /**
   * Latency-adjusted candidate score: Elo minus a latency penalty.
   * 300ms EMA -> -6pts; 17s EMA -> -340pts. Elo moves +/-16..32 per
   * request, so chronic slowness reliably demotes a provider, while the
   * 0.2 EMA alpha keeps a single slow outlier from deciding alone.
   */
  candidateScore(p: string): number {
    return (this.elo.get(p) || 1000) - (this.latencyEmaMs(p) || 0) / 50;
  }

  /**
   * recordProbe — synthetic liveness ping outcome. Updates strike counts
   * and the circuit WITHOUT touching Elo or the request DB (synthetic
   * rows would pollute latency percentiles and inflate Elo). Used by the
   * warm-standby pinger so a dead local backend quarantines before user
   * traffic hits it.
   */
  recordProbe(prov: string, ok: boolean, err = ""): void {
    const now = Date.now() / 1000;
    if (ok) {
      this.fail.set(prov, [0, now]);
      if (this.circuit.get(prov) === "half") {
        this.circuit.set(prov, "closed");
        this.quarantineLevel.set(prov, 0);
        this.health.recordHealing(
          prov,
          "warm-standby",
          "circuit_recovered",
          "half",
          "closed",
        );
      }
      return;
    }
    const [c] = this.fail.get(prov) || [0, 0];
    this.fail.set(prov, [c + 1, now]);
    this.noteError(prov, 0, err || "warm-standby failed");
    if (c + 1 >= 3 && this.circuit.get(prov) !== "open") {
      const level = (this.quarantineLevel.get(prov) || 0) + 1;
      this.quarantineLevel.set(prov, level);
      const backoff = Math.min(
        QUARANTINE_BASE_S * 2 ** (level - 1),
        QUARANTINE_MAX_S,
      );
      this.circuit.set(prov, "open");
      this.circuitOpenUntil.set(prov, now + backoff);
      this.health.recordHealing(
        prov,
        "warm-standby",
        "circuit_opened",
        "closed",
        "open",
        `${c + 1} consecutive probe failures; quarantine level ${level}, backoff ${backoff}s`,
      );
    }
  }

  /** Full quarantine/circuit snapshot for /status. */
  circuitInfo(p: string): {
    state: string;
    quarantine_level: number;
    consecutive_failures: number;
    backoff_s: number;
    open_until: number | null;
    probe_in_s: number | null;
    last_error: { status: number; err: string; at: number } | null;
  } {
    const now = Date.now() / 1000;
    const until = this.circuitOpenUntil.get(p) || 0;
    const open = (this.circuit.get(p) || "closed") === "open";
    return {
      state: this.circuit.get(p) || "closed",
      quarantine_level: this.quarantineLevel.get(p) || 0,
      consecutive_failures: this.consecutiveFailures(p),
      backoff_s: open ? Math.max(0, Math.round(until - now)) : 0,
      open_until: open ? until : null,
      probe_in_s: open ? Math.max(0, Math.round(until - now)) : null,
      last_error: this.lastError.get(p) || null,
    };
  }

  circuitOk(p: string): boolean {
    const st = this.circuit.get(p) || "closed";
    if (st === "closed") return true;
    if (st === "open") {
      if (Date.now() / 1000 > (this.circuitOpenUntil.get(p) || 0)) {
        this.circuit.set(p, "half");
        return true;
      }
      return false;
    }
    return true; // half-open probe
  }

  /**
   * laneDead — dead-lane exclusion for automatic race sets
   * (503-forensics 2026-09-21).
   *
   * A provider whose last 6+ attempts ALL failed (no success resetting the
   * streak) within the last 10 minutes sits out of pickWeighted /
   * freeCandidates / hedgedChain. This catches lanes the circuit breaker
   * intentionally ignores: persistent 429s (never open the circuit by
   * design), 504s to a dead shim whose /models still 200s for the
   * quarantine prober, and hard 401/402/404s between circuit openings.
   * Dead lanes never win races — they only burn the connect budget
   * (kimi-auto's 8s anchors) and steal slots from serving lanes.
   *
   * Self-healing, no operator action: any success resets the consecutive
   * counter in record(), and the dead flag expires 10 minutes after the
   * last failure, so a recovered lane rejoins on its own. Degraded mode
   * (every lane dead) still races the dead lanes rather than serving 503.
   */
  laneDead(p: string): boolean {
    const [c, ts] = this.fail.get(p) || [0, 0];
    if (c < 6) return false;
    return Date.now() / 1000 - ts < 600;
  }

  /**
   * noteEntitlement404 — LOUD permanent bench for a 404'd model id.
   * Logs to stderr (pitchfork logs) and records a healing event so the
   * bench is visible in /status and the DB, not silent.
   */
  noteEntitlement404(prov: string, model: string): void {
    const key = `${prov}:${model}`;
    if (this.entitlementDead.has(key)) return;
    this.entitlementDead.set(key, Date.now() / 1000);
    console.error(
      `[router] entitlement-404 BENCHED ${key} — no retry burn (re-admit: restart or NVIDIA-side relist)`,
    );
    this.health.recordHealing(
      prov,
      model,
      "live",
      "entitlement_benched",
      "404 not-entitled/delisted: model benched for process lifetime, zero retries",
    );
  }

  /** True when the model id was benched by a 404 (fail-fast, no attempts). */
  isEntitlementDead(prov: string, model: string): boolean {
    return this.entitlementDead.has(`${prov}:${model}`);
  }
}

export const state = new Matrix();

/**
 * startQuarantineProber — active health probing for quarantined providers.
 * Every QUARANTINE_PROBE_MS, each provider whose circuit is open and whose
 * backoff has expired gets ONE probe (per-attempt deadline inside `probe`).
 * This makes re-admission proactive instead of waiting for live traffic.
 */
export function startQuarantineProber(
  probe: (p: string) => Promise<boolean>,
): void {
  const tick = async () => {
    const now = Date.now() / 1000;
    for (const p of state.circuit.keys()) {
      try {
        if (state.circuit.get(p) !== "open") continue;
        if (now < (state.circuitOpenUntil.get(p) || 0)) continue;
        const ok = await probe(p);
        if (ok) {
          state.circuit.set(p, "half");
          state.health.recordHealing(
            p,
            "",
            "quarantine_probe_ok",
            "open",
            "half",
            "active re-probe succeeded; admitting traffic",
          );
        } else {
          // Re-open at the next backoff level.
          const level = (state.quarantineLevel.get(p) || 0) + 1;
          state.quarantineLevel.set(p, level);
          const backoff = Math.min(
            QUARANTINE_BASE_S * 2 ** (level - 1),
            QUARANTINE_MAX_S,
          );
          state.circuitOpenUntil.set(p, now + backoff);
          state.health.recordHealing(
            p,
            "",
            "quarantine_probe_failed",
            "open",
            "open",
            `re-probe failed; quarantine level ${level}, backoff ${backoff}s`,
          );
        }
      } catch (e) {
        console.error("[router] quarantine prober error for", p, e);
      }
    }
  };
  setInterval(() => {
    tick().catch((e) => console.error("[router] quarantine prober tick:", e));
  }, QUARANTINE_PROBE_MS);
}
