/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $Choice = {
    properties: {
        index: {
            type: 'number',
            description: `The index of the choice in the list of choices (always 0).`,
            isRequired: true,
        },
        message: {
            type: 'all-of',
            description: `A chat completion message generated by the model.`,
            contains: [{
                type: 'Message',
            }],
            isRequired: true,
        },
        finish_reason: {
            type: 'any-of',
            description: `The reason the model stopped generating tokens. This will be \`stop\` if the model hit a natural stop point or a provided stop sequence, or \`length\` if the maximum number of tokens specified in the request was reached.`,
            contains: [{
                type: 'Enum',
            }, {
                type: 'null',
            }],
        },
    },
} as const;
