/**
 * @sovereign/providers — master provider catalog for the sovereign estate.
 *
 * Single source of truth for: provider definitions (base URL, key env,
 * endpoint adapter per /models shape), live discovery, alias map, curated
 * cold-start seeds, and auto-quarantine. TS consumers import this package;
 * Go consumers use generated/providers.go; Python consumers use
 * generated/providers.json. Both artifacts are regenerated by
 * `bun run build` and verified in sync by the test suite.
 */
export type {
  AdapterId,
  AuthStyle,
  DiscoveredModels,
  ModelAlias,
  ModelSource,
  PersistedCatalog,
  PersistedProviderState,
  ProviderDef,
  QuarantineEntry,
  QuarantineReason,
} from "./types.ts";

export { ADAPTERS, AdapterParseError, adapterFor } from "./adapters.ts";
export type { BuiltRequest, ModelsAdapter } from "./adapters.ts";

export { discover } from "./discovery.ts";
export type { DiscoverOptions, DiscoveryResult } from "./discovery.ts";

export { ModelCatalog, PRUNE_AFTER_MISSES } from "./catalog.ts";

export {
  DEAD_MODEL_IDS,
  MODEL_ALIASES,
  PROVIDER_DEFS,
} from "./data.ts";

export { buildProvidersGo, buildProvidersJson, emitAll } from "./codegen.ts";
export type { CodegenInput } from "./codegen.ts";
