import type { ArchConfig } from "./fleet_types.ts";

export const ARCH_CONFIG: Record<string, ArchConfig> = {
  deepseek2: {
    name: "DeepSeek-V2/V3/R1",
    isMla: true,
    isHybrid: false,
    isRecurrent: false,
    isMoe: true,
    mlaDefault: 2,
    flashAttnRecommended: true,
    cacheTypeK: "q8_0",
    cacheTypeV: "q8_0",
    fusedMoe: true,
    groupedExpertRouting: false,
    attnMaxBatch: 512,
    runtimeRepack: true,
    overrideTensors: ["exps=CPU"],
    extraFlags: ["--parallel", "1"],
  },
  deepseek: {
    name: "DeepSeek-V1",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: true,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: true,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  qwen3next: {
    name: "Qwen3-Next (hybrid)",
    isMla: false,
    isHybrid: true,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  qwen35moe: {
    name: "Qwen3.5-MoE",
    isMla: false,
    isHybrid: true,
    isRecurrent: false,
    isMoe: true,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: true,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  qwen35: {
    name: "Qwen3.5",
    isMla: false,
    isHybrid: true,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  qwen2: {
    name: "Qwen2",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  qwen2moe: {
    name: "Qwen2-MoE",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: true,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: true,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  llama: {
    name: "Llama",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  llama4: {
    name: "Llama 4",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: true,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: true,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  mistral3: {
    name: "Mistral 3",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  mistral4: {
    name: "Mistral 4 (MLA)",
    isMla: true,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 2,
    flashAttnRecommended: true,
    cacheTypeK: "q8_0",
    cacheTypeV: "q8_0",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 256,
    runtimeRepack: false,
    extraFlags: [],
  },
  gemma: {
    name: "Gemma",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  gemma2: {
    name: "Gemma 2",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  gemma3: {
    name: "Gemma 3",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  gemma4: {
    name: "Gemma 4",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  gemma4_mtp: {
    name: "Gemma 4 MTP",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: ["--mtp"],
  },
  mamba: {
    name: "Mamba",
    isMla: false,
    isHybrid: false,
    isRecurrent: true,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: false,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  phi2: {
    name: "Phi-2",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  phi3: {
    name: "Phi-3",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  glm4: {
    name: "GLM-4",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  glm4_moe: {
    name: "GLM-4-MoE",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: true,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: true,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  glm_dsa: {
    name: "GLM-DSA (MLA)",
    isMla: true,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 2,
    flashAttnRecommended: true,
    cacheTypeK: "q8_0",
    cacheTypeV: "q8_0",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 256,
    runtimeRepack: false,
    extraFlags: [],
  },
  cohere2: {
    name: "Cohere 2",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  cohere2_moe: {
    name: "Cohere 2 MoE",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: true,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: true,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  bailingmoe2: {
    name: "BailingMoE2 (Ling/Ring)",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: true,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: true,
    groupedExpertRouting: true,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  granite: {
    name: "Granite",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  granite_moe: {
    name: "Granite MoE",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: true,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: true,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
  unknown: {
    name: "Unknown",
    isMla: false,
    isHybrid: false,
    isRecurrent: false,
    isMoe: false,
    mlaDefault: 0,
    flashAttnRecommended: true,
    cacheTypeK: "f16",
    cacheTypeV: "f16",
    fusedMoe: false,
    groupedExpertRouting: false,
    attnMaxBatch: 0,
    runtimeRepack: false,
    extraFlags: [],
  },
};

export function getArchConfig(arch: string): ArchConfig {
  const key = arch?.toLowerCase().replace(/[^a-z0-9]/g, "") || "unknown";
  if (ARCH_CONFIG[key]) return ARCH_CONFIG[key];
  for (const [k, v] of Object.entries(ARCH_CONFIG)) {
    if (key.includes(k) || k.includes(key)) return v;
  }
  return ARCH_CONFIG["unknown"];
}
