#!/usr/bin/env bun
/**
 * Wire VS Code Insiders, Grok, Antigravity, ide-test → llama-swap :25100 (Bun).
 * Defaults come from live catalog; no hand-maintained GGUF inventories.
 * SSE URL is exported for clients that can auto-discover (Zed already does).
 */
import { homedir } from "os";
import { join } from "path";
import { mkdirSync } from "fs";

import { loadSovereignPorts, requireEnv } from "../lib/ports.ts";
import {
  clientEnvExports,
  listSwapModels,
  pickDefaultModel,
  swapBaseUrl,
  swapModelsSseUrl,
  swapV1Url,
} from "../lib/llama_swap_ssot.ts";

loadSovereignPorts();
const PORT = requireEnv("LLAMA_SWAP_PORT");
const BASE = swapV1Url();
const CHAT = `${BASE}/chat/completions`;
const SSE = swapModelsSseUrl();
const ROOT = swapBaseUrl();
const HOME = homedir();
const SOV = process.env.SOVEREIGN_ROOT || join(HOME, "sovereign");
const SCRATCH =
  process.env.SCRATCH || "/tmp/grok-goal-272520044418/implementer";

function log(msg: string) {
  console.log(`[ide-clients] ${msg}`);
}

const defaultModel = await pickDefaultModel();

// 1) VS Code Insiders — live catalog mirror (not static list)
const r = Bun.spawnSync({
  cmd: ["bun", "run", join(SOV, "src/deploy/code_insiders.ts")],
  stdout: "inherit",
  stderr: "inherit",
  env: process.env,
});
if (r.exitCode !== 0) process.exit(r.exitCode || 1);

// 2) ide-test — OpenAI-compat base only; default model from live pick
const ideTest = join(HOME, "projects/ide-test");
if (await Bun.file(join(ideTest, "README.md")).exists()) {
  await Bun.write(
    join(ideTest, "void-fang/settings.json"),
    JSON.stringify(
      {
        "openai.base_url": BASE,
        "openai.api_key": "not-required-for-local",
        "openai.model": defaultModel,
        "sovereign.models_sse": SSE,
      },
      null,
      2,
    ) + "\n",
  );
  // Zed-fang: same contract as real Zed — llama.cpp + auto_discover, no available_models
  await Bun.write(
    join(ideTest, "zed-fang/settings.json"),
    JSON.stringify(
      {
        language_models: {
          "llama.cpp": {
            api_url: ROOT,
            auto_discover: true,
          },
        },
        agent: {
          default_model: {
            provider: "llama.cpp",
            model: defaultModel,
          },
        },
      },
      null,
      2,
    ) + "\n",
  );
  await Bun.write(
    join(ideTest, "lapce-sovereign/settings.toml"),
    `[ai]
provider = "openai"

[ai.openai]
base_url = "${BASE}"
api_key = "not-required-for-local"
model = "${defaultModel}"
# models_sse = "${SSE}"  # poll /v1/models or subscribe if client supports
`,
  );
  for (const rel of [
    "omnifang/core.ts",
    "zerofang/gobetween.ts",
    "omnifang/devenv.nix",
    "zerofang/devenv.nix",
    "zed-fang/devenv.nix",
    "lapce-sovereign/devenv.nix",
    "void-fang/devenv.nix",
    "scaffold.sh",
    "README.md",
  ]) {
    const p = join(ideTest, rel);
    try {
      let t = await Bun.file(p).text();
      const n = t.replaceAll("127.0.0.1:25001", `127.0.0.1:${PORT}`);
      if (n !== t) await Bun.write(p, n);
    } catch {
      /* missing ok */
    }
  }
  log(`ide-test → ${BASE} default=${defaultModel} sse=${SSE}`);
}

// 3) Grok config.toml — only patch legacy local ports
const grokCfg = join(HOME, ".grok/config.toml");
try {
  let t = await Bun.file(grokCfg).text();
  const n = t
    .replaceAll("127.0.0.1:28080", `127.0.0.1:${PORT}`)
    .replaceAll("127.0.0.1:25001", `127.0.0.1:${PORT}`);
  if (n !== t) {
    await Bun.write(grokCfg, n);
    log("grok config.toml patched legacy local ports");
  }
  log(
    `grok_has_25100=${t.includes("127.0.0.1:25100") || n.includes("127.0.0.1:25100")}`,
  );
} catch (e) {
  log(`grok config skip: ${e}`);
}

// 4) Antigravity + shared client env (includes MODELS_SSE)
const antDir = join(HOME, ".gemini/antigravity-ide");
mkdirSync(antDir, { recursive: true });
const antEnv = join(antDir, "sovereign-llm.env");
const envBody = clientEnvExports(defaultModel);
await Bun.write(
  antEnv,
  `# Generated by sovereign/src/deploy/ide_clients.ts\n${envBody}`,
);
log(`antigravity env → ${antEnv}`);

mkdirSync(join(SOV, ".state"), { recursive: true });
await Bun.write(join(SOV, ".state/client-llm.env"), envBody);
log(`wrote ${join(SOV, ".state/client-llm.env")}`);

// 5) evidence
mkdirSync(SCRATCH, { recursive: true });
const { ok, models } = await listSwapModels();
const settings = JSON.parse(
  await Bun.file(join(HOME, ".config/Code - Insiders/User/settings.json")).text(),
);
const out = {
  port: Number(PORT),
  base: BASE,
  models_sse: SSE,
  default_model: defaultModel,
  list_ok: ok,
  llama_swap_models: models.length,
  "oaicopilot.baseUrl": settings["oaicopilot.baseUrl"],
  "oaicopilot.models": (settings["oaicopilot.models"] || []).length,
  "sovereign.llamaSwap.modelsSse": settings["sovereign.llamaSwap.modelsSse"],
  utility: settings["chat.utilitySmallModel"],
  antigravity_env: antEnv,
  runtime: "bun",
  ssot: "llama-swap live /v1/models + /models/sse",
};
const evidence = join(SCRATCH, "ide-clients.json");
await Bun.write(evidence, JSON.stringify(out, null, 2) + "\n");
console.log(JSON.stringify(out, null, 2));
log(`wrote ${evidence}`);
log("done");
