#!/usr/bin/env bun
/**
 * Wire VS Code Insiders, Grok, Antigravity, ide-test → llama-swap :25100 (Bun).
 */
import { homedir } from "os";
import { join } from "path";
import { mkdirSync } from "fs";

const PORT = process.env.LLAMA_SWAP_PORT || "25100";
const BASE = `http://127.0.0.1:${PORT}/v1`;
const CHAT = `${BASE}/chat/completions`;
const HOME = homedir();
const SOV = process.env.SOVEREIGN_ROOT || join(HOME, "sovereign");
const SCRATCH =
  process.env.SCRATCH || "/tmp/grok-goal-272520044418/implementer";

function log(msg: string) {
  console.log(`[ide-clients] ${msg}`);
}

// 1) VS Code Insiders
const r = Bun.spawnSync({
  cmd: ["bun", "run", join(SOV, "src/deploy/code_insiders.ts")],
  stdout: "inherit",
  stderr: "inherit",
  env: process.env,
});
if (r.exitCode !== 0) process.exit(r.exitCode || 1);

// 2) ide-test
const ideTest = join(HOME, "projects/ide-test");
if (await Bun.file(join(ideTest, "README.md")).exists()) {
  await Bun.write(
    join(ideTest, "void-fang/settings.json"),
    JSON.stringify(
      {
        "openai.base_url": BASE,
        "openai.api_key": "not-required-for-local",
        "openai.model": "beellama/qwen-flash-64k",
      },
      null,
      2,
    ) + "\n",
  );
  await Bun.write(
    join(ideTest, "zed-fang/settings.json"),
    JSON.stringify(
      {
        language_models: {
          openai: {
            api_url: BASE,
            api_key: "not-required-for-local",
            default_model: "beellama/qwen-flash-64k",
          },
        },
      },
      null,
      2,
    ) + "\n",
  );
  await Bun.write(
    join(ideTest, "lapce-sovereign/settings.toml"),
    `[ai]
provider = "openai"

[ai.openai]
base_url = "${BASE}"
api_key = "not-required-for-local"
model = "beellama/qwen-flash-64k"
`,
  );
  // patch TS/nix defaults 25001→25100 if any leftover
  for (const rel of [
    "omnifang/core.ts",
    "zerofang/gobetween.ts",
    "omnifang/devenv.nix",
    "zerofang/devenv.nix",
    "zed-fang/devenv.nix",
    "lapce-sovereign/devenv.nix",
    "void-fang/devenv.nix",
    "scaffold.sh",
    "README.md",
  ]) {
    const p = join(ideTest, rel);
    try {
      let t = await Bun.file(p).text();
      const n = t.replaceAll("127.0.0.1:25001", `127.0.0.1:${PORT}`);
      if (n !== t) await Bun.write(p, n);
    } catch {
      /* missing ok */
    }
  }
  log(`ide-test → ${BASE}`);
}

// 3) Grok config.toml — only patch legacy local ports
const grokCfg = join(HOME, ".grok/config.toml");
try {
  let t = await Bun.file(grokCfg).text();
  const n = t
    .replaceAll("127.0.0.1:28080", `127.0.0.1:${PORT}`)
    .replaceAll("127.0.0.1:25001", `127.0.0.1:${PORT}`);
  if (n !== t) {
    await Bun.write(grokCfg, n);
    log("grok config.toml patched legacy local ports");
  }
  log(`grok_has_25100=${t.includes("127.0.0.1:25100") || n.includes("127.0.0.1:25100")}`);
} catch (e) {
  log(`grok config skip: ${e}`);
}

// 4) Antigravity env
const antEnv = join(HOME, ".gemini/antigravity-ide/sovereign-llm.env");
mkdirSync(join(HOME, ".gemini/antigravity-ide"), { recursive: true });
await Bun.write(
  antEnv,
  `# Generated by sovereign/src/ide_clients_deploy.ts (mise)
export OPENAI_BASE_URL=${BASE}
export OPENAI_API_BASE=${BASE}
export LLM_BASE_URL=${BASE}
export LLAMA_SWAP_URL=http://127.0.0.1:${PORT}
export LLAMA_CHAT_URL=${CHAT}
export SOVEREIGN_LLM=${BASE}
`,
);
log(`antigravity env → ${antEnv}`);

// 5) evidence
mkdirSync(SCRATCH, { recursive: true });
const modelsRes = await fetch(`${BASE}/models`);
const models = modelsRes.ok ? ((await modelsRes.json()) as { data?: unknown[] }) : { data: [] };
const settings = JSON.parse(await Bun.file(join(HOME, ".config/Code - Insiders/User/settings.json")).text());
const out = {
  port: Number(PORT),
  base: BASE,
  llama_swap_models: (models.data || []).length,
  "oaicopilot.baseUrl": settings["oaicopilot.baseUrl"],
  "oaicopilot.models": (settings["oaicopilot.models"] || []).length,
  utility: settings["chat.utilitySmallModel"],
  antigravity_env: antEnv,
  runtime: "bun",
};
const evidence = join(SCRATCH, "ide-clients.json");
await Bun.write(evidence, JSON.stringify(out, null, 2) + "\n");
console.log(JSON.stringify(out, null, 2));
log(`wrote ${evidence}`);
log("done");
