import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdtemp, readdir, readFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { detectMigration, runMigration } from '../src/index.js';
import { listSessionsV2, readSessionSummaryV2 } from './v2-session-scan.js';

const GOLDEN = fileURLToPath(new URL('./fixtures/golden', import.meta.url));
const GOLDEN_HOME = join(GOLDEN, '.kimi');
const HISTORICAL_HOME = join(GOLDEN, '.kimi-historical-config');
const MARKER = join(GOLDEN_HOME, '.migrated-to-kimi-code');
const HISTORICAL_MARKER = join(HISTORICAL_HOME, '.migrated-to-kimi-code');
const WORK_DIR = '/work/golden-proj';

const UUID_RICH = '11111111-aaaa-4bbb-8ccc-111111111111';
const UUID_METADATA = '22222222-aaaa-4bbb-8ccc-222222222222';
const UUID_TITLE_ONLY = '33333333-aaaa-4bbb-8ccc-333333333333';
const UUID_FLAT = '44444444-aaaa-4bbb-8ccc-444444444444';

const FULL_SCOPE = {
  config: true,
  mcp: true,
  userHistory: true,
  skills: true,
  sessions: true,
} as const;

let tgt: string;
beforeEach(async () => {
  tgt = await mkdtemp(join(tmpdir(), 'golden-'));
  await rm(MARKER, { force: true });
  await rm(HISTORICAL_MARKER, { force: true });
});
afterEach(async () => {
  await rm(tgt, { recursive: true, force: true });
  await rm(MARKER, { force: true });
  await rm(HISTORICAL_MARKER, { force: true });
});

async function migrateGolden() {
  const plan = await detectMigration({ sourcePath: GOLDEN_HOME });
  const report = await runMigration({
    plan,
    scope: FULL_SCOPE,
    source: GOLDEN_HOME,
    target: tgt,
  });
  return { plan, report };
}

async function readMigratedState(uuid: string): Promise<{
  title: string;
  isCustomTitle: boolean;
  titleKind: string;
  archived: boolean;
  archivedAt?: number;
  additionalDirs?: string[];
  custom: Record<string, unknown>;
}> {
  const index = (await readFile(join(tgt, 'session_index.jsonl'), 'utf-8'))
    .split('\n')
    .filter((l) => l.length > 0)
    .map((l) => JSON.parse(l) as { sessionId: string; sessionDir: string });
  const entry = index.find((e) => e.sessionId === `ses_${uuid}`);
  expect(entry).toBeDefined();
  return JSON.parse(await readFile(join(entry!.sessionDir, 'state.json'), 'utf-8'));
}

describe('golden fixtures (generated by kimi-cli serializers)', () => {
  it('detects every data class, including historical layouts', async () => {
    const { plan } = await migrateGolden();
    expect(plan.hasConfig).toBe(true);
    expect(plan.hasMcp).toBe(true);
    expect(plan.hasUserHistory).toBe(true);
    expect(plan.hasSkills).toBe(true);
    expect(plan.totalSessions).toBe(4);
    expect(plan.sessionScanFailures).toEqual([]);
    expect(plan.oauthCredentials).toEqual(['kimi-code']);
    expect(plan.detectedMcpOauthServers).toEqual(['golden-remote']);
  });

  it('migrates config faithfully: provider types mapped, oauth ref kept, hooks kept', async () => {
    const { report } = await migrateGolden();
    expect(report.summary.config.migrated).toBe(true);
    expect(report.summary.config.droppedProviders).toEqual([]);
    expect(report.summary.config.droppedModels).toEqual([]);
    expect(report.summary.config.migratedHooks).toBe(1);

    const cfg = await readFile(join(tgt, 'config.toml'), 'utf-8');
    expect(cfg).toContain('default_model = "golden-main"');
    expect(cfg).toContain('type = "openai"');
    expect(cfg).not.toContain('openai_legacy');
    expect(cfg.match(/type = "google-genai"/g)).toHaveLength(1);
    expect(cfg).toContain('type = "vertexai"');
    expect(cfg).toContain('key = "oauth/kimi-code"');
    expect(cfg).toContain('echo golden-hook');
    expect(cfg).toMatch(/\[models\.vllm-mooncake\][\s\S]*?reasoning_key = "reasoning"/);
    expect(cfg).not.toMatch(/\[providers\.vllm\][^[]*reasoning_key/);

    const tui = await readFile(join(tgt, 'tui.toml'), 'utf-8');
    expect(tui).toContain('theme = "dark"');
    expect(tui).toContain('command = "code --wait"');
  });

  it('merges MCP servers and reports the oauth server for reauth', async () => {
    const { report } = await migrateGolden();
    expect([...report.summary.mcp.mergedServers].sort()).toEqual(['golden-remote', 'golden-stdio']);
    expect(report.notices.mcpOauthServersRequiringReauth).toEqual(['golden-remote']);
    const mcp = JSON.parse(await readFile(join(tgt, 'mcp.json'), 'utf-8')) as {
      mcpServers: Record<string, { auth?: string }>;
    };
    expect(mcp.mcpServers['golden-remote']?.auth).toBe('oauth');
  });

  it('never copies OAuth credentials or the MCP OAuth store', async () => {
    const { report } = await migrateGolden();
    expect(existsSync(join(tgt, 'credentials'))).toBe(false);
    expect(existsSync(join(tgt, 'mcp-oauth'))).toBe(false);
    expect(report.notices.oauthLoginsRequiringRelogin).toContain('kimi-code');
  });

  it('copies user history and skills, then writes the completion marker', async () => {
    await migrateGolden();
    const historyDir = await readdir(join(tgt, 'user-history'));
    expect(historyDir).toHaveLength(1);
    expect(existsSync(join(tgt, 'skills', 'golden-skill', 'SKILL.md'))).toBe(true);

    const marker = JSON.parse(await readFile(MARKER, 'utf-8')) as { version: number };
    expect(marker.version).toBe(1);
  });

  it('migrates all four sessions and skips the non-local bucket', async () => {
    const { report } = await migrateGolden();
    expect(report.summary.sessions.sessionsMigrated).toBe(4);
    expect(report.summary.sessions.sessionsFailed).toEqual([]);
    expect(report.summary.sessions.sessionsConflicts).toEqual([]);
    expect(report.summary.sessions.bucketsSkippedNonlocalKaos).toBe(1);
    expect(existsSync(join(tgt, 'sessions'))).toBe(true);
    const index = await readFile(join(tgt, 'session_index.jsonl'), 'utf-8');
    expect(index).not.toContain('55555555');
  });

  it('rich session: nested media, thinking, tool calls, display, title, dirs preserved', async () => {
    await migrateGolden();
    const state = await readMigratedState(UUID_RICH);
    expect(state.title).toBe('Golden rich session');
    expect(state.isCustomTitle).toBe(true);
    expect(state.additionalDirs).toEqual(['/work/golden-extra']);

    const index = (await readFile(join(tgt, 'session_index.jsonl'), 'utf-8'))
      .split('\n')
      .filter((l) => l.length > 0)
      .map((l) => JSON.parse(l) as { sessionId: string; sessionDir: string });
    const dir = index.find((e) => e.sessionId === `ses_${UUID_RICH}`)!.sessionDir;
    const wire = await readFile(join(dir, 'agents', 'main', 'wire.jsonl'), 'utf-8');
    expect(wire).toContain('"image_url"');
    expect(wire).toContain('"imageUrl":{"url":"data:image/png;base64,iVBORw0KGgo=","id":"img-1"}');
    expect(wire).toContain('"audioUrl":{"url":"data:audio/wav;base64,UklGRg=="}');
    expect(wire).toContain('"videoUrl":{"url":"https://media.example.test/v.mp4","id":"vid-1"}');
    expect(wire).toContain('thinking about the attachments');
    expect(wire).toContain('"name":"Shell"');
    expect(wire).toContain('ls -la');
    expect(wire).not.toContain('unsupported content');
  });

  it('metadata session: legacy metadata.json merged with state defaults', async () => {
    await migrateGolden();
    const state = await readMigratedState(UUID_METADATA);
    expect(state.title).toBe('Golden legacy title');
    expect(state.isCustomTitle).toBe(false);
    expect(state.titleKind).toBe('generated');
    expect(state.archived).toBe(true);
    expect(state.archivedAt).toBe(1_735_689_700_000);
    expect(state.custom['auto_archive_exempt']).toBe(true);
  });

  it('title-only session: preserved with its custom title', async () => {
    await migrateGolden();
    const state = await readMigratedState(UUID_TITLE_ONLY);
    expect(state.title).toBe('Golden title only');
    expect(state.isCustomTitle).toBe(true);
  });

  it('flat historical session: migrated with title from the first prompt', async () => {
    await migrateGolden();
    const state = await readMigratedState(UUID_FLAT);
    expect(state.title).toBe('flat era hello');
  });

  it('migrated sessions are discoverable by agent-core-v2 with titles and media', async () => {
    await migrateGolden();
    const sessions = await listSessionsV2(tgt);
    const titles = new Map(sessions.map((s) => [s.id, s.title]));
    expect(titles.get(`ses_${UUID_RICH}`)).toBe('Golden rich session');
    expect(titles.get(`ses_${UUID_METADATA}`)).toBe('Golden legacy title');
    expect(titles.get(`ses_${UUID_TITLE_ONLY}`)).toBe('Golden title only');
    expect(titles.get(`ses_${UUID_FLAT}`)).toBe('flat era hello');

    const rich = await readSessionSummaryV2(tgt, `ses_${UUID_RICH}`);
    expect(rich?.custom?.['imported_from_kimi_cli']).toBe(true);
    expect(rich?.cwd).toBe(WORK_DIR);

    const metadataSummary = await readSessionSummaryV2(tgt, `ses_${UUID_METADATA}`);
    expect(metadataSummary?.archived).toBe(true);
    expect(metadataSummary?.archivedAt).toBe(1_735_689_700_000);

    const index = (await readFile(join(tgt, 'session_index.jsonl'), 'utf-8'))
      .split('\n')
      .filter((l) => l.length > 0)
      .map((l) => JSON.parse(l) as { sessionId: string; sessionDir: string });
    const richDir = index.find((e) => e.sessionId === `ses_${UUID_RICH}`)!.sessionDir;
    const wire = await readFile(join(richDir, 'agents', 'main', 'wire.jsonl'), 'utf-8');
    const mediaKinds = ['"imageUrl"', '"audioUrl"', '"videoUrl"'];
    for (const kind of mediaKinds) {
      expect(wire).toContain(kind);
    }
    expect(wire).toContain('"id":"img-1"');
  });

  it('migrates a historical config.json-only source', async () => {
    const plan = await detectMigration({ sourcePath: HISTORICAL_HOME });
    expect(plan.hasConfig).toBe(true);
    const report = await runMigration({
      plan,
      scope: FULL_SCOPE,
      source: HISTORICAL_HOME,
      target: tgt,
    });
    expect(report.summary.config.migrated).toBe(true);
    const cfg = await readFile(join(tgt, 'config.toml'), 'utf-8');
    expect(cfg).toContain('default_model = "historical-main"');
    expect(cfg).toContain('type = "openai"');
  });
});
